### ISSUE TITLE
[firebase] Recoil 3.0 cannot work with firebase

### ISSUE THREAD

**Issue by namofnoah** [facebookexperimental/Recoil#1053]
Previously it was working with version 2.0 but after I upgrade to version 3.0, it crashed
export const firestoreState = atom({
  key: "firestore", // unique ID (with respect to other atoms/selectors)
  default: firebase.app().firestore(), // default value (aka initial value)
});

export const allMovieState = selector({
  key: "allMovieState",
  get: async ({ get }) => {
    // Get your firestore instance
    const firestore = get(firestoreState);
    // Use it!
    const movies = await firestore.collection("movies").get();
    const movieNames = [...movies.docs].map((doc) => {
      const movieData = doc.data();
      return {
        id: doc.id,
        title: movieData.title,
        assetRef: movieData.assetRef, // refers to the streaming asset
      };
    });
    return movieNames;
  },
});

It said something relating to _frozenObject.

**Comment by drarmstr** [comment]
There were some fixes where Recoil will now properly freeze objects stored as values in selectors in dev mode.  This is done to help catch issues where users may attempt to mutate objects thinking they are changing state whereas all state changes must go through a proper Recoil set.  

First question is if you or firebase is expecting to mutate these objects and if that could be avoided?  If not, does the mutation represent a state change?  If it doesn't then you can workaround the object freezing by maybe storing a handle to the object instead of the object itself or using the `dangerouslyAllowMutability` option for the selector.

**Comment by namofnoah** [comment]
Hi,
I tried it but it still cried out cloud. Here is my setup for firebase:
export const firestoreState = selector({
  key: "firestoreState",
  get: () => {
    return firebase.app().firestore()
  },
  dangerouslyAllowMutability: true,
})

And i got this error: TypeError: Cannot assign to read only property '_settingsFrozen' of object '#<e>'

Version 2.0 is working for this way, is there anyway to workaround?

**Comment by gavingolden** [comment]
I got it to work with the following
> user.state.tsx
```tsx
type UserState = { user: User | null; loading: boolean }

export const userAtom = atom<UserState>({
  key: 'userAtom',
  default: { user: null, loading: true },
  dangerouslyAllowMutability: true,
})
```
> auth-monitor.component.tsx
```tsx
export function useWatchUserState(): void {
  const setUser = useSetRecoilState(userAtom)

  useEffect(() => {
    const sub = firebaseAuth.onAuthStateChanged((user) => {
      setUser({ user, loading: false })
    }),
    return () => {
      sub()
    }
  }, [])
}
```
> root.navigator.tsx
```tsx
export function RootNavigator() {
  useWatchUserState()
  return (
   // ...
  )
}
```
