### ISSUE TITLE
effects_UNSTABLE only fires once

### ISSUE THREAD

**Issue by mjuopperi** [facebookexperimental/Recoil#1134]
I'm not sure if I'm misunderstanding how this feature is supposed to work, but consider I have the following atom:

```js
export const testAtom = atom({
  key: "testAtom",
  default: 1,
  effects_UNSTABLE: [() => console.log("hello")],
});
```

and in a react component:

```jsx
const App () => {
  const [val, set] = useRecoilState(testAtom);
  return (<button onClick={() => set(val + 1)}>{val}</button>);
}
```

`effects_UNSTABLE` only runs when the app mounts. I thought that I could catch the `onSet` and uipdate backend with that, but I can't seem to get it to fire ever.

**Comment by BenjaBobs** [comment]
Since the effect can do more things, you need to take in an object with a `onSet` property as argument, so you can hook it up.
The initial function block is just for initialization of the effect, and during this initialization you can setup a function to be fired each time the atom value is set.

See https://recoiljs.org/docs/guides/atom-effects#logging-example which does exactly what you're trying to do. 🙂

**Comment by mjuopperi** [comment]
Ah! Now I got it (I hope)! 

`x => console.log(x)` will do nothing, because I need to call the destructured `onSet` function.

I was going for the minimal function for debugging purposes but I guess I had a typo somewhere before.
