### ISSUE TITLE
Save a snapshot to the atom Error

### ISSUE THREAD

**Issue by ty-bt** [facebookexperimental/Recoil#1153]
Save a snapshot to the atom
Error
Cannot assign to read only property '_refCount' of object

demo: https://codesandbox.io/s/xenodochial-feather-rxn50?file=/src/App.js

v0.2 no Error

**Comment by drarmstr** [comment]
You are getting this error because objects stored in atoms or used as selector values are frozen in development.  This is to help catch bugs where users may try to mutate objects for state changes without properly setting the atom and thus updating downstream selectors or subscribed components may not be updated or re-rendered properly.  To override this and allow storage of mutable objects you can use the `dangerouslyAllowMutability: true` option when creating the atom.

Also, note that you should explicitly provide a `default` option when creating the atom with the initial default value.
