### ISSUE TITLE
Atom Default Value derived from prop?

### ISSUE THREAD

**Issue by LorenDorez** [facebookexperimental/Recoil#1166]
Is there any way to initialize an atom with its default value coming from a Prop? 

We currently are using ReactJS.net for SSR. While I understand SSR isnt support yet do you have an idea when this will be? Currently it looks like the setRecoilState calls are not done for SSR so the response just comes in with blank values for places that were using the atoms.

I have tried to use the initializeState on the <RecoilRoot> but our app setup has a very deeply nested tree structure and very dynamic so its difficult to try and set initializeState on the <RecoilRoot> because the children views change.

**Comment by drarmstr** [comment]
The default value itself can't come from a prop because the same atom could be used in multiple components which could pass in different values. 

One option could be to store a placeholder value as the default and use the prop as a fallback in the component.  e.g.:
```jsx
const myAtom = atom({key: 'MyAtom', default: null});

function MyComponent({defaultValue}) {
  const value = useRecoilState(myAtom) ?? defaultValue;
  ...
}
```

However, it is also possible to initialize atoms outside of the React component hierarchy.  If you are having trouble using the `initializeState` approach then [Atom effects](https://recoiljs.org/docs/guides/atom-effects#asynchronous-storage-persistence) offer another approach to providing an initial value that can be specified as part of the atom defition.
