### ISSUE TITLE
Selector throws an error on build version

### ISSUE THREAD

**Issue by philohelp** [facebookexperimental/Recoil#118]
Hello
Thanks for the great job, I really like recoil. Although the todo list example code works fine in development mode, adding the selectors makes the app crash in production version. I made a repo to show what it does : https://github.com/philohelp/recoil-todos
```
git clone https://github.com/philohelp/recoil-todos recoil-todos
cd recoil-todos
yarn global add serve
serve -s build
```
<img width="310" alt="Capture d’écran 2020-05-20 à 02 17 53" src="https://user-images.githubusercontent.com/12623963/82391289-433f6000-9a41-11ea-9d5d-f12d46acbee4.png">

How is it possible to fix this ?

**Comment by davidmccabe** [comment]
There's a bug in the "terser" build step that we're using for the build which causes it to output invalid code. We've seen several problems because of this. In the meantime please use the development bundle, and we are looking into alternatives to terser that may be more correct (suggestions welcome on this). I'm very sorry for the inconvenience. Thanks for reporting this issue.
