### ISSUE TITLE
[Feature request] Conditionally cache the response when using asynchronous data queries

### ISSUE THREAD

**Issue by ibarapascal** [facebookexperimental/Recoil#1465]
## background

Currently, we have the [asynchronous data queries](https://recoiljs.org/docs/guides/asynchronous-data-queries) which enable us to fetch data and save them at the same time.

as long as the request params keep the same, the response could be cached, which is quite nice.

and there are also methods that could let us `refresh` the cache [asynchronous-data-queries/#query-refresh](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-refresh)

## enhancement

Currently, there is a method to limit the cached content which is named `cachePolicy_UNSTABLE`  [ref](https://recoiljs.org/docs/api-reference/core/selector/)

there is also the unstable API [useRecoilRefresher_UNSTABLE](https://recoiljs.org/docs/guides/asynchronous-data-queries/#userecoilrefresher) which would let us re-request without cache inside a handler.

However, in some real-world cases, we may need to **turn off the cache based on the response value itself directly** as well. 

currently:

- 1. request with params
- 2. got an error, response cached
- 3. page redirect to another page then come back
- 4. re-request with the same params
- 5. success, but the previous response is cached

would be nice if we have an API that let us:

- 1. request with params
- 2. got an error, DO NOT cache based on the response value itself

if there are existing methods that would allow us to do that elegantly, please let me know, thanks to you all.

## example

currently, we have to do it like this

```tsx
const { data, code } = useRecoilValue(acquireGame);

const refresh = useRecoilRefresher_UNSTABLE(acquireGame);

useEffect(() => {
  code !== 200 && refresh();
}, [code, refresh]);

return (
  <div>
    {code === 200 && <>...</>}
  </div>
)
```

maybe we could have something like this?

```tsx
const { data, code } = useRecoilValue(acquireGame, { cache: code === 200 });
```

**Comment by drarmstr** [comment]
In general it is dangerous not to cache at all (note the minimal [cache policy](https://recoiljs.org/docs/api-reference/core/selector/#cache-policy-configuration) is `most-recent`).  This is in part because the value may be referenced by a set of other dependencies and components and we would not want to issue a new queries for each.  Additionally, we would not want to control caching policy from a particular hook as the selector cache is global across hooks and even RecoilRoot stores.

Using the refresher API allows you to achieve custom retry policies.  It is [extended in 0.6](https://github.com/facebookexperimental/Recoil/pull/1514/files) to allow you to make recoil callbacks for more self-contained refresher policies.

Another option you have is using atoms instead of selectors for modeling queries and using [atom effects](https://recoiljs.org/docs/guides/atom-effects) to monitor and handle error responses.
