### ISSUE TITLE
Read current atom state in atom effect

### ISSUE THREAD

**Issue by mikonse** [facebookexperimental/Recoil#1477]
A nice to have feature for atom effects would be the ability to read the current atom state.

As far as I have seen atom effects currently can only read the state / metadata of other atom via the `getPromise`, `getLoadable` and `getInfo_UNSTABLE` arguments passed to the atom effect.  Using `getPromise` with the current atom leads to the error `Unhandled Rejection (Error): Recoil selector has circular dependencies` which makes sense. 

My use case for this feature is the following. I use atom effects to update my local state upon websocket notifications from the server.
```javascript
const someState = atom({
    key: "someState",
    default: selector({
        key: "someState/default",
        get: async ({ get }) => {
            return await fetchStateFromServer();
        }
    }),
    effects_UNSTABLE: [
        ({ setSelf, }) => {
            ws.subscribe("someState", () => {
                // register a notification listener at the server via websocket, wrapper will call the provided callback upon a notification
                fetchStateFromServer().then(result => {
                    // here I would like to read the current atom state to do be able to do a partial state
                    // update without re-fetching the whole thing from the remote server
                    setSelf(result);
                });
            });

            return () => {
                ws.unsubscribe("someState");
            };
        }
    ]
})
```

Since some of the state this atom is holding can be larger and only small parts need to be updated upon a server notification, reading the current atom state would enable me to only do a partial update and merge the locally held state with a partial update from the server.

E.g. add a callback `getSelf` to the atom effect parameters which then simply returns the current atom state.

If there is a way to do this currently I'd be thankful for a pointer.

**Comment by honzabrecka** [comment]
I suppose it's already supported as `setSelf` accepts callback which retrieves current state:

```js
setSelf: (
    | T
    | DefaultValue
    | Promise<T | DefaultValue> // Only allowed for initialization at this time
    | ((T | DefaultValue) => T | DefaultValue),
  ) => void
```

**Comment by mikonse** [comment]
After digging around a bit I agree, it is actually possible to either use the `getPromise` or `getLoadable` hooks for the current atom or use `setSelf` via a callback. Testing it with a vanilla `atom` and `atomFamily` also works fine and I can retrieve the current value.

There seems to be a bug when using atoms or atom families with selectors as default values.
In this minimal example:
```javascript
export const atomTest = atom({
    key: "atomTest",
    default: selector({
        key: "atomTest/default",
        get: ({get}) => {
            return "foobar"
        }
    }),
    effects_UNSTABLE: [
        ({ setSelf }) => {
            setSelf(currVal => {
                console.log("curr val atom test:", currVal);
                return "newval";
            });
        }
    ]
})
```

the current value returned from the `setSelf` callback will always be `{}` an empty object instead of the string set by the default selector. The same happens when using atom families with a default selector family. It should not be due to a race condition with the selector as putting a sleep before the setSelf call yields the same result.

**Comment by drarmstr** [comment]
Yes, as @honzabrecka points out you can use the updater form of `setSelf()` by passing in a function.  It is also possible to get the current value using `getLoadable()` or `getPromise()` with the provided `node` parameter:

```jsx
const myEffect = ({node, getLoadable}) => {
  someAsync(() => {
    const loadable = getLoadable(node);
  });
};
```

By itself this should not introduce any circular dependencies as getting the current state does not actually subscribe anything, so that error should be unrelated.

**Comment by mikonse** [comment]
Should I open a new issue for the problem I described above or should we track it here? Also might consider reopening the issue since there still might be a slight issue when using the feature with selectors as atom defaults.

**Comment by drarmstr** [comment]
Ah, yes, if there is an issue with using atoms that have selector defaults then let's re-open the issue for that.

**Comment by drarmstr** [comment]
Note that atoms with selector defaults are a bit complicated.  That feature should probably be removed from the base atom implementation and provided as an explicit wrapper to help keep things simpler and properly set expectations...  When you give an atom a selector default it actually creates a wrapper selector that checks the value of the base atom, if it is `DefaultValue` then it uses the provided default selector value, otherwise the value stored in the provided selector.

That is why if you use the node returned from the `atom()` factory with `getLoadable()` or `getPromise()` in the effect it is actually using the wrapper selector and why you see the error about circular dependencies.  However, the `node` passed into the atom effect is actually the real atom.  So, using `node` actually will work, as my example above.  But, when the atom is not yet set you will just get a `DefaultValue` object instead of the current value of the default selector.

**Comment by DevonStern** [comment]
@drarmstr just reading through this and, based on the last activity on this issue, it sounds like it should actually have been re-opened. Unless it's already been addressed, of course.

**Comment by yuriyyakym** [comment]
I was forced to use `selectorFamily` as a default value for `atomFamily, since it is the only way of getting `useRecoilRefresher` to work.

But now I am not able to `getPromise` in effects, it returns the `DefaultValue` always, even though atom data is set (I am sure about it, because I see data in UI).

Before, when an async function was used as a default `atomFamily` value, everything worked as expected, but I was unable to refetch data on-demand.

**Comment by yuriyyakym** [comment]
This is the only way in which I am able to get a value:

```ts
const someSelectorFamily = selectorFamily<string, string>({
  key: 'some-selector',
  get: (id: string) => () => Promise.resolve(`Fetch data by id: ${id}`),
});

const createSomeEffect =
  (id: string): AtomEffect<string> =>
  ({ getPromise }) => {
    getPromise(someSelectorFamily(id)).then(console.log);
  };

const someAtom = atomFamily<string, string>({
  key: 'some-atom',
  default: someSelectorFamily,
  effects: [createSomeEffect],
});
```
