### ISSUE TITLE
Cannot destroy RecoilRoot

### ISSUE THREAD

**Issue by Qquanwei** [facebookexperimental/Recoil#1538]
App.jsx

```js
    <RecoilRoot>
      <Suspense fallback="loading...">
        <Router>
          <Switch>
            <Route exact path="/" component={Index} />
            <Route path="/comic/:id" component={Comic} />
          </Switch>
        </Router>
      </Suspense>
    </RecoilRoot>
```

Comic.jsx

```js
      <RecoilRoot>
        <Component  {...props}/>
      </RecoilRoot>
```

when I switch route from `comic` to `index`, and then switch `index` to `comic` , comic component selector not recompute (I'm sure comic component is remount). I expect  refresh but not, is a bug or feature ?

**Comment by drarmstr** [comment]
You don't include any selectors in your example.  However, it sounds from your question that you are expecting selectors to re-evaluate when a a component using them is re-mounted?  A selector's value is evaluated based on its dependencies and cached, it won't re-evaluate unless a dependency changes.  However, you can now use a hook like `useRecoilRefresher_UNSTABLE()` to manually invalidate a selector cache.  See [this documentation](https://recoiljs.org/docs/guides/asynchronous-data-queries#query-refresh)

**Comment by Qquanwei** [comment]
@drarmstr I expect the `RecoilRoot` **re-mount** will destroy selector cache, but it not.

**Comment by drarmstr** [comment]
> @drarmstr I expect the `RecoilRoot` **re-mount** will destroy selector cache, but it not.

Correct.  selector caches are global and used across multiple roots.  Because selector evaluation functions should be idempotent without side-effects, and only rely on dependency inputs, it should generally not matter that the cache is shared.  If a selector needs to be re-evaluated with the same inputs it should provide the same output.  However, that contract is sometimes relaxed when selector evaluations themselves leverage external caches or query external systems.  To accommodate this is why we introduced the refresher API to clear the selector cache, such as to force a re-query.

**Comment by Qquanwei** [comment]
@drarmstr When performing server-side rendering, each request needs to have an independent selector, so it is hoped that the idempotency of the selector can be completed only under the RecoilRoot, and different RecoilRoots do not need to maintain the idempotency of the selector.
