### ISSUE TITLE
How to initialize an atom with component prop data?

### ISSUE THREAD

**Issue by PAK90** [facebookexperimental/Recoil#1664]
Is it possible to intialize an atom, or atomFamily, using data from props inside a component? Atom effects have no access to component props, and I can't get access to that data outside of component props.

Alternatively, if I initialize an empty atomFamily, is there a 'proper' way to write initial prop data to it using `useSetRecoilState()` or something similar, for example on my root component's initial load (with a useEffect listening to `[]`)?

**Comment by drarmstr** [comment]
Generally that's not built-in because there would be races depending on which component happen to render an atom first.  You can do it with `useEffect()`, as you point out.  

Also check out [this example](https://recoiljs.org/docs/recoil-sync/implement-store#example-syncing-with-react-props) from the upcoming Recoil Sync library.
