### ISSUE TITLE
`snapshot.getInfo_UNSTABLE().subscribers.components` always empty

### ISSUE THREAD

**Issue by nutstick** [facebookexperimental/Recoil#1684]
Hi, I try to get the components that subscribe to atom to virtualize it in a devtool. But I found that `subscribers.components` always return empty array regardless.

```tsx
const snapshot = useRecoilSnapshot();

useEffect(() => {
  console.log(Array.from(snapshot.getInfo_UNSTABLE(myAtom).subscribers.components))
}, [snapshot])
```

How can I get subscribed components properly?

Reproducable codesandbox

- https://codesandbox.io/s/use-recoil-snapshot-subscribers-components-9uxfdy

**Comment by drarmstr** [comment]
That is because you are looking at a `Snapshot` which is a snapshot of read-only atom state and never has Component subscribers.  To see the component subscribers for the current `<RecoilRoot>` you can use the [`useGetRecoilValueInfo()`](https://recoiljs.org/docs/api-reference/core/useGetRecoilValueInfo) hook.
