### ISSUE TITLE
Is it safe to use latest version if they contain "alpha"?

### ISSUE THREAD

**Issue by a-tonchev** [facebookexperimental/Recoil#1807]
I am using recoil in production, so far without any single issue. But when I check for updates with yarn outdated I noticed that the latest version is 0.7.3-**alpha**.2 

Is it safe to upgrade from 0.6.1 to the latest version of recoil, or is it better to wait for the "real" upgrade?

**Comment by noritheduck** [comment]
Hey @a-tonchev, Alpha generally means that the version may contain errors and have some instability so it is always a use at your own risk version. I hope that helps!

**Comment by catnose99** [comment]
The problem is alpha version is tagged with **latest**.
This means `0.7.3-alpha.2` is installed when you simply run `npm install recoil`.


<img width="793" alt="" src="https://user-images.githubusercontent.com/34590683/169955818-171ded3d-db37-4d48-bc5c-7b04e75e9445.png">


In general, another tag such as `alpha` or `canary` should be used for alpha versions.

**Comment by a-tonchev** [comment]
Yes - exactly that is the problem. Usually alpha/beta versions are tagged with `next` not with `latest`
