### ISSUE TITLE
[recoil-sync] syncEffect({write:() =>{}}) isn't call

### ISSUE THREAD

**Issue by parweb** [facebookexperimental/Recoil#1878]
Here the codesandbox
https://codesandbox.io/s/pensive-ride-pjp0bt?file=/src/App.js:656-664

I try to update the $todo with a new value
but the callback ```write``` on syncEffect don't fire up

In which case this callback ```write``` is call ?

```js
const [todo, set_todo] = useRecoilState($todo);
set_todo({ id: 2, title: "two" })
```

```js
const $todo = atom({
  key: "todo",
  default: {},
  effects: [
    syncEffect({
      storeKey: "Todo",
      refine: object({ id: nullable(number()), title: nullable(string()) }),
      read: ({ read }) => ({ id: read("id"), title: read("title") }),
      write: ({ write, reset }, newValue) => {
        console.log({ newValue });

        if (newValue instanceof DefaultValue) {
          reset("id");
          reset("title");
        } else {
          write("id", newValue.id);
          write("title", newValue.title);
        }
      }
    })
  ]
});
```

**Comment by drarmstr** [comment]
This is because the custom `<RecoilSync>` store in your implementation doesn't implement writing.  Since there is no `write` prop the store doesn't try to write anything so it doesn't need to check with the atoms on how to write.  Here's an update to your test that adds the write functionality:

https://codesandbox.io/s/unruffled-euclid-zxx5l0?file=/src/App.js
