### ISSUE TITLE
 reading an atom value in a selector without subscribing to changes

### ISSUE THREAD

**Issue by SunilChiluvuri** [facebookexperimental/Recoil#1923]
Is there a way to read an atom value in a selector without subscribing to changes.

I tried useRecoilCallback but got a message that it can only be used in a react component or custom hook. 
So can't be used in the "get" of a selector.

**Comment by drarmstr** [comment]
You can't get the value of another atom/selector in the "get()" of a selector without subscribing.  That's because selector evaluations should be idempotent, which means they should always produce the same value given the same set of inputs/dependencies.  If the atom value a selector depends on changes then the selector should be reevaluated.  You can consider passing in values via selector family parameters instead of direct dependencies if you want more control over reevaluation.
