### ISSUE TITLE
Recoil sync doesn't work with async functions

### ISSUE THREAD

**Issue by nahtnam** [facebookexperimental/Recoil#1978]
Hello,

I'm trying to use `recoil-sync` with an async store. I'm having an issue where I have a simple recoil syncer like this:

```
<RecoilSync
          storeKey="test"
          read={(key) => {
            console.log("called read sync")
            return new DefaultValue()
          }}
          write={async ({ diff }) => {
            console.log("writing sync", diff)
          }}>
```

and this works great, but the second I add `async` to the read function, it goes into an infinite loop with the error:

```
       Warning: Can't perform a React state update on a component that hasn't mounted yet. This indicates that you have a side-effect in your render function that asynchronously later calls tries to update the component. Move this work to useEffect instead.
    at Batcher (test.8a546aea.js:65026:24)
    at RecoilRoot_INTERNAL (test.8a546aea.js:65097:32)
    at RecoilRoot (test.8a546aea.js:65212:13)
    at Recoil (test.8a546aea.js:62028:13)
    at PersistGate (test.8a546aea.js:73231:9)
    at Provider (test.8a546aea.js:34250:21)
    at Redux (test.8a546aea.js:73194:13)
    at Suspense
    at div
    at Document (test.8a546aea.js:3324:13)
    at MyApp
```

Again, without async, that error doesn't show up and the app works fine.

I tried creating a reproducible example, but I couldn't get CodeSandboxy to work with recoil-sync. It always errors with `useRecoilStoreID is not a function
`. However, here is the code: https://codesandbox.io/s/recoil-counter-demo-forked-c6d2ho?file=/src/App.js If you add `async` before the function name it breaks and infinitely renders (in my local app). Without `async` it works fine.

**Comment by drarmstr** [comment]
The codesandbox example was not working because it was using an old version of Recoil, update it to the latest (0.7.5).  I updated the sandbox and added `async` and it appears to work  https://codesandbox.io/s/recoil-counter-demo-forked-f18ed9?file=/src/App.js

However, that example wasn't actually syncing the atoms so I updated it to include `syncEffect()` and then also wrapped the sync with a `<React.Suspense>` to handle the async state: https://codesandbox.io/s/recoil-counter-demo-forked-ip4sdh?file=/src/App.js

Also, please note that the [`write()`](https://recoiljs.org/docs/recoil-sync/api/RecoilSync#write-interface) callback itself should not be `async`.

**Comment by nahtnam** [comment]
@drarmstr Sorry for the half-assed codesandbox, it was late for me. I was able to figure out why that codesandbox you provided worked but it didn't for me. I had my suspense wrapper outside of recoil root instead of inside. Moving it seems to have fixed it

**Comment by nahtnam** [comment]
Why can't `write` be async? Can I trigger an async function just without awaiting it?

**Comment by drarmstr** [comment]
> Why can't `write` be async? Can I trigger an async function just without awaiting it?

You can fire off async writes if you want a write-through approach, but the `write()` callback itself should be void, it should not be `async` or return a `Promise`.  Recoil Sync will not block or schedule anything after your async write.
