### ISSUE TITLE
Cannot use hooks from within recoil selector

### ISSUE THREAD

**Issue by sabres207** [facebookexperimental/Recoil#2039]
When I try to call custom hook from within a recoil selector (for example from its get function), I get the "Invalid hook call" error.
This only happens if I actually use the get property passed to the get function, i.e

this will work just fine:
```
select({key: 'key', get: () => {
  useCustomHook()
}})
```

but this will fail:
```
select({key: 'key', get: ({get}) => {
  const something = get(somethingState)
  useCustomHook()
}})
```

The thing is, we are wrapping fetch api to have some behaviors we need from it, and one of those behaviors is displaying an error message (which is set by recoil state) whenever we receive 401 or 403 http codes.
So what happens now is I can't actually call this fetch wrapper from within my selectors, cause it won't accept this custom hook from within the selector.

Would love to hear any suggestion to handle it.
For example, how would you fetch data with react-query useQuery hook inside recoil selector if you'd use both of them?

Thank you!

**Comment by tpAtalas** [comment]
It is because it breaks the rule of hook. 

https://reactjs.org/docs/hooks-rules.html

I would use custom hook along with useRecoilCallback.

**Comment by sabres207** [comment]
Would appreciate an explanation why does it breaks the rules of hooks?
And what would would be the way to go for fetching data from within a Selector, when you use some kind of hook for that in your project (i.e useQuery of react-query)
Don't see how useRecoilCallback helps in this situation.

**Comment by drarmstr** [comment]
Hooks can only be called from the render functions of React components or other hooks.  They should not be called from callbacks, effects, or otherwise outside of a component render.  They cannot be conditionally called.  So, it's not appropriate to use hooks from selector evaluations.  [`useRecoilCallback()`](https://recoiljs.org/docs/api-reference/core/useRecoilCallback) can be useful to create a hook which can call other hooks and define a callback which can get/set selectors/atoms.  The [`recoil-sync`](https://recoiljs.org/docs/recoil-sync/introduction) library can also support a pattern which [creates a store](https://recoiljs.org/docs/recoil-sync/implement-store#example-syncing-with-react-props) from a component that can use props or hooks.
