### ISSUE TITLE
Duplicate atom key warning when used from multiple bundles

### ISSUE THREAD

**Issue by atanasster** [facebookexperimental/Recoil#213]
For 0.0.8, I am getting the following blocking error (was working fine with 0.07):

`recoil.development.js:117 Uncaught TypeError: Cannot destructure property 'error' of 'undefined' as it is undefined.`

Two issues afaics: 
1. It displays the wrong error, since there isnt a third parameter in the call from registerNode: 
https://github.com/facebookexperimental/Recoil/blob/22b42bbc0366bf748b4265735eb4b6c90c90ff1f/src/core/Recoil_Node.js#L84
2. The actual error (Duplicate atom key ..)  it wants to display is not correct, since I have only one of this key registered (it is not duplicated), however the package is called from two bundles.

**Comment by atanasster** [comment]
@drarmstr thanks for linking this issue to a PR. However I also have a second part - that the error 'Duplicate atom key .' is not correct. 

Should I file a new issue about that, or do you have any feedback on this?

**Comment by Shmew** [comment]
Are you using HMR? That will trigger that error I believe.

**Comment by atanasster** [comment]
I am using hmr however the error shows without hmr being invoked (no files are changed, just loading the app generates the error)

**Comment by drarmstr** [comment]
@atanasster I don't think we've seen the duplicate key issue outside of HMR, but it sounds like it may be due to the atom being created twice from the two bundles?

**Comment by drarmstr** [comment]
@atanasster - Please re-open this issue if you continue to see a problem without HMR.

**Comment by hmtri1011** [comment]
![image](https://user-images.githubusercontent.com/16288424/87665281-dde1c400-c790-11ea-86db-f25ba45b2746.png)
Hi all, I got this warning when trying `Recoil` with `NextJS`. This happens every time I try refresh with new page.

I think it might be HMR problem because it happened on development only, but I want to know how I do a singleton pattern for `atom` to prevent this warning on development. 

Thanks!

**Comment by martinop** [comment]
any news?

**Comment by parweb** [comment]
time to re-open the issue :/

**Comment by rosko** [comment]
Experiencing the same issue as @hmtri1011 described.

**Comment by deshario** [comment]
@hmtri1011 Any solution ?

**Comment by anoveskey-dte** [comment]
I felt it's worth mentioning this. If you declare your atom/selector inside the same file it is being used, you will see this warning whether your have hot module replacement enabled or not. It is best to import it.

**Comment by cenguidanos** [comment]
Yes @anoveskey-dte ! Thanks, it works, but, if you're on NX workspace you have to create a  separated  lib and import atoms/selectors from there, also with Nex.js.

**Comment by ivanjeremic** [comment]
> I felt it's worth mentioning this. If you declare your atom/selector inside the same file it is being used, you will see this warning whether your have hot module replacement enabled or not. It is best to import it.

Do you mean this for Nextjs? I try to somehow solve this issue in my Nextjs project is there any way of doing this currently?

**Comment by juanpprieto** [comment]
I'd love to be able to suppress these warnings in NextJS too.

I get the warnings both during dev (prob due to HMR) and also during build time (much more noticeable) as its probably included in every chunk that next generates. 

However, in both instances everything seems to work just fine.

Thanks!
