### ISSUE TITLE
Behavior passing iterables as selectorFamily parameter

### ISSUE THREAD

**Issue by ACampbell12** [facebookexperimental/Recoil#359]
I'm encountering strange behavior when passing an iterable object as a selectorFunction parameter. 

### Context:
The situation calls for wanting to access an unknown number of atom states. My first thought was to simply call `useRecoilValue(atomState(id))` in a loop for each _id_ that was required....but Hook's requirement of running at the top level prevents that as an option.

Luckily selectorFamily exists, so I tried defining one such as this:

```
export const dependencyState = selectorFamily({
  key: "DependencyState",
  get: (ids) => ({ get }) => ids.map((id) => get(atomState(id))),
});
```

However I encounter a runtime error telling me that _ids_ is undefined. This happens whenever I attempt to call an Array prototype function. I can log, return, and test _ids_ for iterability, and all the behavior is expected, but I always get an "undefined" error when I invoke a function on the object.

### Work-Around

I currently worked around it by altering my selectorFamily to: 
```
export const dependencyState = selectorFamily({
  key: "DependencyState",
  get: (ids) => ({ get }) => {
    ids = Array(ids);
    return ids.map((id) => get(atomState(id)));
  },
});
```

but this feels like poor form and I'm getting warnings about `Cannot update a component ('Batcher') while rendering a different component` which feels like low-level React behavior I simply don't grasp yet.

I checked with the Recoil documentation and the only caveat I see for the parameter passed to selectorFunction is that it be serializable, which mine definitely is.

### Question
Is what I'm experiencing expected behavior? And if so, is there a better solution than above (to include a completely different approach to my atom/selector setup)?

P.S. I'm still new to React, let alone Recoil, so please feel free to correct me if this is completely poor choice in design. Thanks!

**Comment by drarmstr** [comment]
The warning is an unrelated known issue due to a recent change from React that's being tracked with #12 

As the [`selectorFamily()`](https://recoiljs.org/docs/api-reference/utils/selectorFamily) docs mention, there are restrictions on the types of values that can be used as parameters as they are serialized.  They should support arrays and iterables, I added a simple unit test for an iterable here (#362).  But, `map()` isn't part of the iterable protocol, so I'd be curious what type of object you are using?  an array or something else?  I added a unit test for array parameters here (#363)  Anyway, this approach definitely isn't optimal for large objects due to the serialization, it will end up also doing an `Array.from()`

But, if your goal is to just be able to loop around using atoms, then what about using [`waitForAll()`](https://recoiljs.org/docs/api-reference/utils/waitForAll)?
```jsx
useRecoilValue(waitForAll(Array.from(ids).map(atomState)));
```

**Comment by ACampbell12** [comment]
@drarmstr, thanks for the quick reply. Point taken on the looping and using `waitForAll()`. The performance gain from skipping the serialization makes sense and it's clean.

As for the issue that I was encountering though, I apologize because it was user error. 

Thanks for the help!
