### ISSUE TITLE
[ Question ]. Why doesn't "set" on writable/bidirectional selectors cause an infinite loop when setting atom state upstream?

### ISSUE THREAD

**Issue by rebo** [facebookexperimental/Recoil#364]
Just trying to conceptually understand this.

If a selector can subscribe to an atom, but can also mutate that atom by being bi-directional using `set` why doesn't an infinite loop occur?

I'm probably missing something obvious here but cannot quite figure how how this is resolved.

Thanks

**Comment by drarmstr** [comment]
A selector depending on an atom value and setting an atom's value isn't sufficient to establish an infinite loop since there's no loop.  If you set a selector that sets an atom which then causes the selector to reflect that value, then anyone else subscribing to the selector will now see the new value, but there's no loop there.  A selector reflecting a new value from a change in its dependencies doesn't initiate the selector to "set" and change upstream.  If you setup some component to subscribe to the selector changing values, and then immediately try to set or change the selector again, such as in an effect, then you would get a loop.  But, that would be the same as if you just used an atom, React state, or anything else.

**Comment by rebo** [comment]
Right, got it thanks very much for the quick and clear reply.
