### ISSUE TITLE
How to use ApolloClient in Selector

### ISSUE THREAD

**Issue by Capsicum42** [facebookexperimental/Recoil#389]
Thanks for providing the great library.

I try to load asynchronos data as described in the example with an Apollo GraphQl client.
 This works:
```
const client = new ApolloClient({
    cache: new InMemoryCache(),
    link: new HttpLink({
      uri: 'http://localhost:1337/graphql',
    })
  });

const currentPatientsQuery = selector({
    key: 'Patients',
    get: async ({get}) => {
        const response = await client.query ({
            query: PATIENTS,
            fetchPolicy: "network-only",
        });
      return response.data.patients;
    },
  });
```
Now I want to use the client I had created in my App.tsx.
Normaly I would use:
`  const client = useApolloClient();`

But this is not working. 

Is it possible to use other react hooks together with recoil ?

Thanks for your help.

**Comment by lvivcss** [comment]
You just need to call your selector in component, like `const x = useRecoilValue(currentPatientsQuery )`

**Comment by mondaychen** [comment]
I think you'll need to wrap your app with `ApolloProvider` in order to use your `client`. I don't think this is related to Recoil.

**Comment by zbyte64** [comment]
Hooks need to be inside components, so what you will need to do is write a component and atom dedicated to retrieving the client from the context and storing the client for other selectors to use.

**Comment by dcantu96** [comment]
@mondaychen Im currently having this question, I'm trying to run a useApolloClient hook inside a selectoryFamily and strangely it lets me do this. However, like @zbyte64 stated, hooks need to be inside components so what would be the correct approach to make this work?

**Comment by mondaychen** [comment]
@dcantu96 Like you and @zbyte64 said, we should always use hooks inside a component. It might work when you use them otherwise, but can break in some edge cases or future releases, depending on how exactly it's implemented.

We don't have an easy way to make it work appropriately at the moment. But we've been working on a sister library called "recoil-sync" to address this issue, with which you can sync a piece of external data to an atom. Our current plan is to release it in March, but you can [preview the doc here](https://recoiljs.org/docs/recoil-sync/introduction). We appreciate feedbacks on the design, docs and source code. I'll also ping the thread once it's released.
Thanks for the support!
