### ISSUE TITLE
A hook for getting previous value of a state

### ISSUE THREAD

**Issue by baymac** [facebookexperimental/Recoil#409]
Is there a way you get the previous value of a state with a hook? My use case would be updating a state `A` if a state `B` has changed. Using useEffect to subscribe the state change can be erroneous as component gets mounted and unmounted then mounted again and useEffect is triggered but it doesn't necessarily mean state `B` has changed.

**Comment by drarmstr** [comment]
There are techniques for using React hooks to get previous values of React state which could also work for Recoil state.  For example: https://usehooks.com/usePrevious/

**Comment by baymac** [comment]
@drarmstr Thanks for the link but I was not able to make it work. Here is a codesandbox of the same. https://codesandbox.io/s/damp-dawn-xbdtt?file=/src/Table.js.

How to reproduce this?

1. Select a value from dropdown in the first step (Data sources)
2. Go to next step (Tables)
3. Select a value from dropdown in this step
4. Go back, then go next again.

You will see that table state is reset again by useEffect hook in Tables.js.

The problem is the usePrevious hook always returns undefined. I am not sure if I am doing things the right way, please let me know what you think.

**Comment by g1nk1-m** [comment]
@baymac The reason for the `usePrevious` hook always returning undefined is because the `useEffect` is fired only once because of the dependency array being `[dataSource]` which doesn't change with re-render. If you remove the dependency, you can see that the previous state value is correctly being updated. That said, `usePrevious` hook only works well for managing states within the same component. In your example, you're checking for state changes in a different component, so either use `usePrevious` hook in the Root component and pass the previous value as props or modify the usePrevious hook to make it work with global states by using a separate atomFamily for managing previous states.
```javascript
// atoms.js
export const prevState = atomFamily({
  key: "prevState",
  default: ""
});
```
```javascript
// usePrevious.js
import {useEffect} from 'react';
import { useRecoilState } from "recoil";
import { prevState } from "./atoms";

export default function usePrevious(value, lookup) {
  const [prevData, setPrevData] = useRecoilState(prevState(lookup));
  useEffect(() => {
    setPrevData(value);
  }, [value, lookup]); // Only re-run if value changes
  // Return previous value (happens before update in useEffect above)
  return prevData;
}
```
and the `usePrevious` hook is called as 
```javascript
// Table.js
// the key of the state is used for lookup into atomFamily
const prevDataSource = usePrevious(dataSource,dataSourceState.key);
```

**Comment by baymac** [comment]
@g1nk1-m Thanks, nice solution 👏
