### ISSUE TITLE
#request A way to get an atom's default value

### ISSUE THREAD

**Issue by geoyws** [facebookexperimental/Recoil#425]
Instead of having to export const a default value of the atom, it'd be nice to be able to get the default value via a prop.

**Comment by drarmstr** [comment]
What do you mean by "via a prop"?  Can you provide an example of where you would like to see the default value?

**Comment by Shmew** [comment]
I think in this case it would be something like where an atom has a nested async selector for the default value, such that the default value isn't known at compile time. Then they would be able to "ask" what the default value was before they decide to reset it or something.

**Comment by drarmstr** [comment]
If an atom is using a selector as a default, then you can get the value of the selector to see what the default would be.

**Comment by Shmew** [comment]
Yeah I'd agree in taking the selector out of the atom definition if they need the value, but that's my guess at why they would want the feature.

**Comment by geoyws** [comment]
> I think in this case it would be something like where an atom has a nested async selector for the default value, such that the default value isn't known at compile time. Then they would be able to "ask" what the default value was before they decide to reset it or something.

Yes precisely this 😅. Recoil has made state management so much easier for us but I was wondering if there was a utility we could use to get the default value of the atom at runtime without resetting the atom. This might save some typing.

Suggestion: useRecoilDefaultState()
```JavaScript
export const localeState = atom({
  key: 'locale',
  default: 'en-MY'
})

export const someComponent = () => {
  const [locale, setLocale] = useRecoilState(localeState)
  const localeDefault = useRecoilDefaultState(localeState) // suggestion

  return (<>
    <div>Customer 1: {locale}</div>
    <div>Customer 1's Default Locale: {localeDefault}</div>
  </>)
}
```

Right now our workaround would be like this: 
```JavaScript
export const localeDefault = 'en-MY'

export const localeState = atom({
  key: 'locale',
  default: localeDefault
})
```

**Comment by drarmstr** [comment]
A couple issues with this:  What if the default value is a Promise?  The `RecoilValue<T>` represents an interface that abstracts both atoms and selectors such that the user should not be aware of which implementation is being used and selectors do not have a "default" value.

**Comment by geoyws** [comment]
Apologies if my suggestions aren't suitable, I'm no veteran <:)

> A couple issues with this: What if the default value is a Promise? 

Perhaps here we could just allow the default value to be a Promise that can be .then()-ed or awaited later, in the spirit of flexibility.

> The `RecoilValue<T>` represents an interface that abstracts both atoms and selectors such that the user should not be aware of which implementation is being used and selectors do not have a "default" value.

Perhaps we could allow for selectors to fall back to a default value while waiting for the promise to resolve (if users choose to not use <Suspense/>).

```JavaScript
export interface ReadOnlySelectorOptions<T> {
    key: string;
    get: (opts: { get: GetRecoilValue }) => Promise<T> | RecoilValue<T> | T;
    dangerouslyAllowMutability?: boolean;
    default?: any; // suggestion
}
```

**Comment by drarmstr** [comment]
> Perhaps here we could just allow the default value to be a Promise that can be .then()-ed or awaited later, in the spirit of flexibility.

That wouldn't help with your use-case, since you couldn't use the async value from the synchronous React rendering function.  We return a [`Loadable<T>`](https://recoiljs.org/docs/api-reference/core/Loadable) type in some similar cases where the user needs synchronous access to a potentially asynchronous value.  See [`useRecoilValueLoadable()`](https://recoiljs.org/docs/api-reference/core/useRecoilValueLoadable).  We could offer some `useRecoilValueDefault()` or `useRecoilValueDefaultLoadable()` hook to get the default value.  But, I'm not sure the value is there to justify the extra complication to the API, even if we solved the selector symmetry issue below:

> Perhaps we could allow for selectors to fall back to a default value while waiting for the selector to resolve (if users choose to not use Suspense). We could also allow for selectors to have a default value in the case of errors perhaps (with impure functions). Perhaps even with pure functions, there may be a use case where users just want to have a default selector value without deference to dependencies upstream the data-flow graph. Really don't want to rock the boat here if the gains are minimal 😅.

While that may be an interesting capability for a default for selectors, it wouldn't really match the semantics of the `default` for an atom.  An atom default is used when the atom has not been set to a specific value, and may itself by async.  It is only used if the atom was never set or was reset.  In the future, if we initialize or set an atom to an async value, we would want the opportunity to then set the atom to a pending state to take advantage of Suspense.  The semantics you describe are more like a suspense fallback for this node, and actually this fallback concept could also be applied to atoms.  So, while interesting, it doesn't address the symmetry issue.

**Comment by drarmstr** [comment]
Closing for now without a proposal with defined semantics.

**Comment by hellosmithy** [comment]
It would be useful to be able to infer the default value somehow, or check if the current value passes an equality check with the default value. An example would be conditionally deciding to persist an atom based on wether it equals the default value or not.

**Comment by diegonakamashi** [comment]
O problema de nao passar o person pra false é que a tela fica assim:
![image](https://user-images.githubusercontent.com/377335/147759940-d5895171-5213-4707-90fa-7d3fa92c49b8.png)

**Comment by drarmstr** [comment]
Also see #1459
