### ISSUE TITLE
Creating Inline Atoms Fail (and with wrong error message) 

### ISSUE THREAD

**Issue by ohansemmanuel** [facebookexperimental/Recoil#444]
Hi there! 

## Problem

Creating an atom inline i.e passing it to `useRecoilState` seems to fail: 
```diff
- const countAtom = atom({
- key: "count",
- default: 0,
- });

- const [activePlanet, setActivePlanet] = useRecoilState(countAtom);
+ const [activePlanet, setActivePlanet] = useRecoilState(atom({
+ key: "count"
+ default: 0
+}));
```

## Expectation 
Following React's mental model I assumed this would work perfectly - like lazily initializing the initial value to the `useState` hook. 

## Error Message 
<img width="597" alt="CleanShot 2020-07-06 at 19 30 36@2x" src="https://user-images.githubusercontent.com/10930234/86622001-7329cf00-bfbf-11ea-915f-5e38b602ae01.png">

The error message "Duplicate atom key 'count'"  doesn't seem accurate - at least from a user's perspective, as the key is indeed unique - just passed inline.

**Comment by Shmew** [comment]
The problem with inlining the atom is any subsequent re-render or call to a function will try to recreate the atom resulting in a duplicate.

**Comment by drarmstr** [comment]
As @Shmew points out, it is not valid to create atoms inline in a render function.  Calling `atom()` creates an atom which represents shared state.  If you call it in a render function then you will be creating a new shared piece of state for each execution.  Since you give it the same key each time it errors that you are using duplicate keys.  Instead, create your atom outside of the render function and share the returned instance will all components that share that state.

Ideally we might eventually want to have lint rules to warn against this..
