### ISSUE TITLE
[Feature Request]: Devtools, SideEffects management, Serialization / Deserialization

### ISSUE THREAD

**Issue by shivamd20** [facebookexperimental/Recoil#49]
😍😍😍
I am immensely impressed by the simplicity of this library and looking forward to using it in actual projects.

There are a few things that I'd love to have : 

1. A Devtool, similar to redux dev tool where you can see the state graph and modify them accordingly.
2. A clean and ergonomic way to handle side-effects. (No middleware magic) 
3. Serialization/Deserialization of whole state tree/graph.

**Comment by drarmstr** [comment]
Yup!  internally we have persistence and dev tool support.  We're working on polishing the API so we can publish it and example libraries using it.

**Comment by polemius** [comment]
@shivamd20 Good feature request! While we are waiting for devtool support I've wrote the logger for recoil https://github.com/polemius/recoil-logger

**Comment by davidmccabe** [comment]
For serialization and deserialization, use the `useTransactionObservation` and `useSetUnvalidatedAtomValues` hooks (unstable, API will likely change for the better in the next few weeks).

For the actual serialization/deserialization part, internally some of our apps use the Transit library 
It's a flexible, hassle-free, and performant way to serialize. Maybe there's something newer that's emerged in the JS ecosystem since I last looked into this, I don't know. It works great for us. https://github.com/cognitect/transit-js

**Comment by davidmccabe** [comment]
For side effects, I would suggest just having a component with `useEffect`. Let me know if there's something you'd like to do that isn't readily handled in that manner.

**Comment by ramblingenzyme** [comment]
I suppose you could write hooks to wrap any mixing of Recoil state and side effects, but couldn't this also be done with selectors directly if the set function could be async so all the responsibility stays in Recoil and you can't mess it up by using the selector instead of the hook?

Just throwing this out more than anything else, I'd understand wanting to lean on React more.

**Comment by adnux** [comment]
I have to agree that if recoil could handle side-effects in a "graceful" standardized way (once i call a, then call b in case of success or c in case of failure), i would not just help avoid misunderstandings from developers, but also eliminates the need to have another library to deal with that!

**Comment by drarmstr** [comment]
It would be interesting to see examples of side-effects that can't cleanly be captured with the existing API and effects to evaluate requirements.

**Comment by ulises-jeremias** [comment]
Hi everyone! I'm working on this right now!

- [Recoil Devtools](https://www.npmjs.com/package/recoil-devtools)
- [Recoil Logger](https://www.npmjs.com/package/recoil-devtools-logger)

Both packages could be found in this [Github repository](https://github.com/ulises-jeremias/recoil-devtools), in which i'm creating devtools for recoil based on existing redux devtools and other projects. In future, more devtools and docs will be available!
