### ISSUE TITLE
Compilation for Vite.js

### ISSUE THREAD

**Issue by Rykian** [facebookexperimental/Recoil#509]
Hello,
I was messing around with Vite.js (with TypeScript & React) and tried to use Recoil, but importing the lib seems broken with Rollup or Vite.
I got a `Uncaught SyntaxError: import not found: atom` in console when I try to use atom.

I've just modified the default page by adding to the default Vite/React/TS template (`yarn create vite-app --template react-ts`)
```js
import { atom } from 'recoil'

// [...]

const state = atom({
  key: 'state',
  default: ''
})
```

Here is a demo repo : https://github.com/Rykian/vitejs-test-recoil
You just have to run a `yarn install` & `yarn dev` and go to http://localhost:3000 to see the error.

**Comment by Kayyow** [comment]
It looks like you can import it using the default import `import Recoil from 'recoil'` I don't know why but this works.
As a workaround you can :
```
import Recoil from 'recoil'
...
const { atom } = Recoil
```

**Comment by JeremyRH** [comment]
For dev builds, Vite uses [@rollup/plugin-commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs) which attempts to convert CommonJS to ES modules.

In this case, Vite uses @rollup/plugin-commonjs to transform Recoil's [index.js](https://unpkg.com/browse/recoil@0.0.10/dist/index.js) file. That file does not have "named exports" in the CommonJS style: `exports.atom = ...`. This causes named exports in the ES module format to not be generated.

Changes are coming that could fix this issue. I'm not familiar enough with Vite to know if it takes advantage of packages that output a ES modules.

**Comment by mondaychen** [comment]
I agree with @JeremyRH. With next release Recoil will come with a ES format build and should thus can work with Vite. Unfortunately I haven't got time to play with Vite myself (although have been watching Evan You bragging about it for a while). It's much appreciated if you can try build latest master branch and test with Vite. Otherwise, let's wait for next release and see if it works.

I'll investigate and fix this issue if it's still broken on next release.

**Comment by balboFK** [comment]
Hello @mondaychen, any news on this? I'm migrating a project to use vite and vitest and having this same issue with recoil.
On test runs it throws the 'ReferenceError: Window is not defined'.

**Comment by mondaychen** [comment]
@balboFK sounds like a different issue. Can you paste in more details of that error?

**Comment by balboFK** [comment]
@mondaychen thanks for the reply, of course I can!

This is the stack trace of the error: 

```
ReferenceError: Window is not defined
 ❯ shouldNotBeFrozen node_modules/recoil/cjs/recoil.js:5642:40
 ❯ deepFreezeValue node_modules/recoil/cjs/recoil.js:5653:36
 ❯ maybeFreezeValueOrPromise node_modules/recoil/cjs/recoil.js:7292:11
 ❯ baseAtom node_modules/recoil/cjs/recoil.js:7277:3
 ❯ atom node_modules/recoil/cjs/recoil.js:7627:12
 ❯ src/presentation/modules/stock/query-by-label-stock/components/atoms.ts:12:47
     10| const { atom } = Recoil
     11| 
     12| export const productInfoAndBalanceStockState = atom({
       |                                               ^
     13|   key: 'productInfoAndBalanceStockState',
     14|   default: {
 ❯ async src/presentation/modules/stock/query-by-label-stock/components/by-filter/components/by-filter-table/by-filter-table.tsx:12:31
```
A print aswell on the Vitest throw.

![image](https://user-images.githubusercontent.com/87539237/149922952-797a539b-9dbd-45df-9b49-34a38cb8b586.png)

All components that import an atom of any kind is throwing this error. 
Thanks!

**Comment by mondaychen** [comment]
@balboFK This is happening because your test environment does not have `Window` defined. If I remember it right, Vite does support Jest by default, and is using its own testing framework. Looks like that testing framework does not define `Window` by default. 

I'll discuss with team and hopefully submit a fix this week.

**Comment by balboFK** [comment]
@mondaychen thanks for the reply! I'll be looking foward to it.
Vite does support Jest but since Jest needs files to be plain .js, you would also need .babel or other compiler to achieve that.
Jest has experimental features to handle esm but I wasn't able to move our current tests sucessfully trough method, hence the move to Vite!

**Comment by mondaychen** [comment]
@balboFK submitted PR #1571 to fix your issue
