### ISSUE TITLE
set is not updating component after await or in callback on writable selector

### ISSUE THREAD

**Issue by skflowne** [facebookexperimental/Recoil#531]
I've come across an issue where calling `set` after an `await` call will not propagate the state update to my component.
I've also tried doing it with `then` and `catch` and it's the same problem.

At first I was implementing the real code with Firebase, then I cut as many sources of problems as possible by removing anything Firebase related and even the `try` `catch` block 

This is what I have after simplifying
```js
export const addQuestion = (question) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(true)
        }, 2000)
    })
}
```

```js
import { selector, atom } from "recoil"

import { addQuestion } from "../../firebase/questions.service"

export const createQuestionState = atom({
    key: "create-question-state",
    default: {
        loading: false,
        created: false,
        error: null,
    },
})
export const createQuestionMutation = selector({
    key: "create-question-mutation",
    get: ({ get }) => {
        return get(createQuestionState)
    },
    set: async ({ get, set }, question) => {
        console.log("create question", question)

        set(createQuestionState, { loading: true, error: null, created: false })
        await addQuestion(question)
        console.log("resolved", get(createQuestionState))
        set(createQuestionState, { loading: false, error: null, created: true })
        console.log("after set", get(createQuestionState))
    },
})
```

The code does run and I can see all logs, the state is set correctly, but the component never gets any update past the `await` call

Here is the component
```js
import React, { useState } from "react"
import Button from "../ui/Button"
import { useRecoilState } from "recoil"
import { createQuestionMutation } from "../../state/api/questions"

const QuestionCreate = () => {
    const [question, setQuestion] = useState({
        title: "",
        description: "",
    })

    const [createState, createQuestion] = useRecoilState(createQuestionMutation)

    console.log("createState", createState)

    const onSubmit = (e) => {
        e.preventDefault()
        createQuestion(question)
    }

    const handleChange = (e) => {
        e.persist()
        setQuestion((question) => {
            return {
                ...question,
                [e.target.name]: e.target.value,
            }
        })
    }

    return (
        <div>
            {createState.loading && <p className="bg-blue-500 text-white">Creating...</p>}
            {createState.created && <p className="bg-green-500 text-white">Created</p>}
            {createState.error && <p className="bg-red-500 text-white">{createState.error}</p>}
            <form className="flex flex-col items-center w-4/5 mx-auto" onSubmit={onSubmit}>
                <input
                    className="border w-full p-2 my-1"
                    type="text"
                    placeholder="Your question..."
                    name="title"
                    value={question.title}
                    onChange={handleChange}
                />
                <textarea
                    className="border w-full h-48 resize-y"
                    name="description"
                    value={question.description}
                    onChange={handleChange}
                ></textarea>
                <Button type="submit">Ask question</Button>
            </form>
        </div>
    )
}

export default QuestionCreate
```

Here is the ouput when I open the app, type in "test" as title and click submit
```js
// ... more of the first line
createState {loading: false, created: false, error: null} // component updates with default state
create question {title: "test", description: ""} // set resolver function gets called
createState {loading: true, error: null, created: false} // component updates to loading state
createState {loading: true, error: null, created: false} // same
resolved {loading: true, error: null, created: false} // promise resolves
after set {loading: false, error: null, created: true} // state has been updated

// I would expect to see createState { loading: false, error: null, created: true } here and the component to update but nothing happens
```

I also tried `useRecoilValue` directly on the `atom` in the component, but it's the same

Is this a bug or am I doing something wrong ?

**Comment by eLeontev** [comment]
looks like here is a missed case for `recoil`
component's subscriptions are fired only during main thread (synchronously), any async setter will not raise the component's updates.

The next flow is implemented: 
1. initial callback with update
2. -> setup empty set of affected states
3. -> perform fired setter 
4. -> add affected changes state to affected set
5. -> fire subscriptions of affected state (components)

or in pseudocode with steps
```javascript
let stateSetter = async ({set, get}, args) => {
  set(state, {loading: true}) // 5
  await set(state, {loading, false}) // 7 setter is called after subscribtions are fired
}

let setDerivedState = (args) => {
  let affectedStates = new Set(); // 2
  let set = (state, value) => affectedStates.add(state.key); // 3
  stateSetter({set, get}, args)  // 4
  fireSubscription(affectedStates) // 6
}

setDerivedState(args) // 1
```

As possible fix in the lib: after each call of `set` the affected subscription should be called (simply call step 6)
but imho I'm not sure the lib was designed to support such side effects
 
Since the reason is based on the lib side the best way would be to refactor your case e.g. to combination of atom and custom hook
```javascript
export const createQuestionState = atom({
    key: 'create-question-state',
    default: {
        loading: false,
        created: false,
        error: null,
    },
});

export const useCreateQuestionWithLoader = (createQuestionState, question) => {
    const [state, setState] = useRecoilState<any>(createQuestionState);

    // the original logic placed inside the `selector` now moved to the callback
    return [
        state,
        useCallback(async () => { // performace optimisation
                try {
                    setState({ loading: true, created: false, error: null });
                    await addQuestion(question);
                    setState({ loading: false, created: true, error: null });
                } catch (error) {
                    setState({ loading: false, created: false, error });
                }
        }, [setState, question]),
    ];
};
```

**Comment by skflowne** [comment]
Thanks for clarifying what's happening, your fix does work as expected.

I feel like what I expect Recoil to be and what it actually is are different things.
I was expecting to have the same ease of use as when you query with a `selector`, and it automatically gives you a state object and the data when it's ready.

Here, instead I have to use an `atom` to keep track of the state of the request "manually" and also create a custom hook to make it work.

Is Recoil not intended to handle this kind of use case ?

**Comment by drarmstr** [comment]
Ideally TypeScript should be complaining with your example because the selector `set()` method is not async and should return void instead of a Promise.

Anyway, yes, Recoil selectors don't support async `set()` methods.  The `set()` is intended to provide immediate synchronous state updates to trying to change the state of the selector.  If you would like to asynchronously set values, though, you can do so from a simple callback or with a hook wrapper as @eLeontev described.  If you have more complex scenarios where you need to inspect atom/selector values between async steps you can also use the `useRecoilCallback()` hook for advanced async usage.

The example approach from @eLeontev should work.  Another alternative might be to store the atom state with just the simple question, and then use an async derived selector to represent the results of setting the question:
```jsx
const questionState = atom<?Question>({
  key: 'Question',
  default: null,
})

const questionCreatedState = selector<boolean>({
  key: 'QuestionCreated',
  get: async ({get}) => {
    const question = get(questionState);
    if (question == null) {
      return false;
    }
    await addQuestion(question);
    return true;
  }
});

function MyComponent() {
  const isQuestionCreated = useRecoilState(questionCreatedState);
  ...
}
```
With this approach changing the `questionState` atom to a new question would cause the derived selector to attempt to asynchronously add it and the state of the `questionCreatedState` selector could be inspected to see if the question was created or not.  It would use React Suspense to indicate a loading state and would throw errors if `addQuestion()` had thrown any errors.  You could use `useRecoilStateLoadable()` to handle those conditions synchronously.  Just tossing some ideas around.
