### ISSUE TITLE
Using setTimeout inside selector

### ISSUE THREAD

**Issue by atulmy** [facebookexperimental/Recoil#552]
I'm trying to reset the atom value inside a selector like so:
```javascript
import { atom, selector } from 'recoil'

// notification
const notification = atom({
  key: 'notification',
  default: {
    success: false,
    message: '',
  },
})

// common notification
export const commonNotification = selector({
  key: 'commonNotification',

  get: ({get}) => get(notification),

  set: ({set, reset}, newValue) => {
    set(notification, newValue)

    setTimeout(() => {
      reset(notification)

      console.log('setTimeout')
    }, 2000)
  }
})
```

However I'm getting the console `setTimeout` but the `atom` is not reset. Calling `reset` outside of `setTimeout` immediately resets the `atom` but not when inside `setTimeout`. Any idea how can I achieve this or alternative way to implement this?

**Comment by CaffeinatedCM** [comment]
From what I can tell the set function cannot be async:

Your set function gets called [here](https://github.com/facebookexperimental/Recoil/blob/master/src/recoil_values/Recoil_selector_OLD.js#L462) and the nodes that you've updated in it get returned a couple lines down (https://github.com/facebookexperimental/Recoil/blob/master/src/recoil_values/Recoil_selector_OLD.js#L466) which eventually gets put into the [updated tree](https://github.com/facebookexperimental/Recoil/blob/565878be3abdf51bf16bc1a8b6a0a6c9bb9bc44b/src/core/Recoil_RecoilValueInterface.js#L105).

Since your call to `reset()` is happening after that initial call, the node doesn't get put into the list of updated nodes

**Comment by CaffeinatedCM** [comment]
This answer looks related: https://github.com/facebookexperimental/Recoil/issues/531#issuecomment-679419116

**Comment by drarmstr** [comment]
Correct, the `get()` method can be async, but not the `set()`.  Unfortunately it seems our current TypeScript types are not catching this.  However, you can still use `setTimeout()` for a delayed using the setter:

```jsx
function useSetWithDelayedReset() {
  const setNotification = useSetRecoilState(notification);
  const resetNotification = useResetRecoilState(notification);
  return newValue => {
    setNotification(newValue);
    setTimeout(() => resetNotification(), 2000);
  };
}
```

And elsewhere in a component:
```jsx
  const setWithDelayedReset = useSetWithDelayedReset();
  setWithDelayedReset(newValue);
```
