### ISSUE TITLE
Hook naming somewhat confusing?

### ISSUE THREAD

**Issue by andyWynyard** [facebookexperimental/Recoil#556]
With regards to the naming of the hooks, they were - to begin with - a bit confusing. I might be wrong, but would it be better to have them names something like...

`useRecoilState()`   all good, this is fine and matches with hooks nicely. 
`useRecoilValue()` => `useRecoilGet()` or `useRecoilGetState()`  Not too big a deal this one.
👇 this and ☝️ this would be nice to match `useRecoilGetState()` and `useRecoilSetState()`
`useSetRecoilState()` => `useRecoilSetState()`  Essentially all Recoil hooks to be prefixed with `useRecoil...()`
`useResetRecoilState()` => `useRecoilResetState()`  As above ☝️  
`useGotoRecoilSnapshot()` => `useRecoilGotoSnapshot()` As above ☝️  

These arent really huge deals, just some suggestions for consistency 🤷‍♂️

**Comment by suren-atoyan** [comment]
I just started investigating Recoil (I love it), and to be honest, the first thing I noticed is the possible improvement of naming convention. I'll write down the same thing you've written, just in a more "expressive" way.

| current version  | sugested version |
| ------------- | ------------- |
| useRecoilState  | useRecoilState  |
| useRecoilValue  | useRecoilGetState  |
| useSetRecoilState  | useRecoilSetState  |
| useResetRecoilState  | useRecoilResetState  |
| useGotoRecoilSnapshot  | useRecoilGotoSnapshot  |

**Comment by suren-atoyan** [comment]
I've just found [this](https://github.com/facebookexperimental/Recoil/issues/270)

**Comment by andyWynyard** [comment]
@suren-atoyan thanks for linking, yes, an extension of that conversation it seems. Hoping the conversation continues.

**Comment by drarmstr** [comment]
Thank you very much for the feedback on the hook naming.  We do have some usability concerns on the current hook names and are in fact considering some rename proposals.  But we don't want to be too disruptive in changing the interface so would only consider this after some priority features/fixes we are working on.  We're actually considering removing the `Recoil` branding from the hooks.  We'll be getting more feedback on this, but just not at this time, since we want to focus on some priority work and avoiding disruption.  So, I'm going to close this issue for now. But, we are taking this feedback into consideration.
