### ISSUE TITLE
[TypeScript] Using class instances as atom values

### ISSUE THREAD

**Issue by david-wb** [facebookexperimental/Recoil#574]
Hi, I apologize in advance as this is a support question, since I was unable to get help on stackoverflow. 

My team is trying to store typescript class instances as atom state values. After getting the state value using hooks, we'd like to copy and then mutate the object by calling methods on it. The code looks something like this:

```
  const [config, setConfig] = useRecoilState<ConfigClass>(configAtom);

  const updateConfig = () => {
    const updatedConfig = _.cloneDeep(config);
    updatedConfig.setProperty1('A');
    updatedConfig.setProperty2('B');

    setConfig(updatedConfig);
  }
  ...
```
The problem here is that doing this results in TypeScript errors such as

`TypeError: attempted to get private field on non-instance
`

It seems the config value received from the `useRecoilState` hooks isn't a normal instance of the class. What is the best way around this problem?

Thank you!

**Comment by drarmstr** [comment]
cc @csantos42

**Comment by wuzzeb** [comment]
I think the problem is that the constructor is not being called on the cloned object, so likely problem is with the cloneDeep call, not recoil.  The way typescript private fields work is that each instance must register itself in the global private field map which happens during the constructor.  You get the error "TypeError: attempted to get private field on non-instance" when a constructor is not called.

See https://www.aaron-powell.com/posts/2020-01-23-typescript-ecmascript-class-private-fields/ for where the error is coming from, the privateMap doesn't have an instance.

As to a fix, you would probably need to implement the cloning manually, calling a constructor on the object.

**Comment by david-wb** [comment]
@wuzzeb Thanks for explaining. It makes sense to me now. I will plan to add a .copy() method to the object in question rather than use cloneDeep to get around this issue.
