### ISSUE TITLE
TransactionObserver/Snapshots - Get entire state as an object?

### ISSUE THREAD

**Issue by u382514** [facebookexperimental/Recoil#584]
I'm getting confused on the documentation for TransactionObserver/Snapshots and have not been able to hunt down valid examples. I can't seem to figure out how to just get the entire state from a snapshot and/or previous snapshot as an object to be able to do a compare/diff. 

Can you good folks lead me in the right direction? 

Thank You!

**Comment by drarmstr** [comment]
We don't want to expose the state as a raw object as we are working on optimizations to avoid storing and copying full state for each snapshot.  But, you can use the `getNodes_UNSTABLE()` method to iterate nodes, particularly `getNodes_UNSTABLE({'isModified: true})` for getting the set of atoms which have changed since the previous batch transaction for diffing.  Then, for each atom, you can use the `getLoadable()` method to get the state for that atom in the snapshot.
