### ISSUE TITLE
Todos example add dropdown

### ISSUE THREAD

**Issue by itaysmalia** [facebookexperimental/Recoil#611]
Lets say I am using the todos app like the docs example [here](https://recoiljs.org/docs/basic-tutorial/atoms) (using an atom for todoList and an atom for each todo item) but I want to add a simple dropdown with all todos texts, I am using Semantic-ui so i can't create a component for dropdown option (and useRecoilValue there), because  I need to pass and options array of `{text,key,value}`. how can i solve this problem?

**Comment by drarmstr** [comment]
I'm not familiar with [Semantic UI](https://semantic-ui.com/).  But, if you really want you could enumerate all of the todo items in the list component.  Because React doesn't allow looping over hooks you can't just loop over `useRecoilValue()` for each item.  But, you could use [waitForAll()](https://recoiljs.org/docs/api-reference/utils/waitForAll) to get all todo items with a single `useRecoilValue()` lookup.  With this approach, the list will re-render if any todo item changes since it will subscribe to all of them for updates.
