### ISSUE TITLE
reorder list with recoil

### ISSUE THREAD

**Issue by hodev-dev** [facebookexperimental/Recoil#654]
I just started to learning recoiljs and I'm trying to implement reorder list but I'm getting full list re render .
**ok so this is the code:**

```typescript
const listAtom = atom({
  key: "list",
  default: [
    {
      id: "1a",
      component: Text,
      state: 'first'
    },
    {
      id: "2a",
      component: Text,
      state: 'second'
    },
    {
      id: "3a",
      component: Text,
      state: 'third'
    }
  ]
});

```
then i make recoil state
```typescript
  const [list, setList] = useRecoilState<any>(listAtom);

```
then I re oreder them like this
```typescript
  const onDragEnd = (result: any) => {
    // dropped outside the list
    if (!result.destination) {
      return;
    }
    const newlist= reorder(
      list,
      result.source.index,
      result.destination.index
    );
    setList([
      ...newlist
    ]);
  }
```
**but still i get full list re render like this**: 

![image](https://user-images.githubusercontent.com/68442704/96144915-8975ee00-0f11-11eb-8d14-ebcfe9bbc224.png)

### React dev tools highlights re renders

**Comment by drarmstr** [comment]
Is your concern that you see all list items being re-rendered after the re-order?  The subscriptions to re-render components are at an atom granularity.  Since you have a single `listAtom` with the entire list, it means the entire list will re-render.  A pattern often used is to store the individual list items in an `atomFamily()` and the array of item IDs in a list atom.  Then, you could have individual components in the list just subscribe to the list item for their ID.  That will cause just that item to re-render if the contents of the list item change.  However, changes to the list ordering itself would still cause the container of list items to re-render.

**Comment by hodev-dev** [comment]
So for example if I had array of object I can create state dynamically for each object in array. Can you give me hint or example how it can be done? Because documents for atom family are not complete
