### ISSUE TITLE
Use initialiseState with atomFamily

### ISSUE THREAD

**Issue by jacques-blom** [facebookexperimental/Recoil#675]
I'm playing around with persisting and rehydrating state with Recoil.

The current blocker is that I can't set `atomFamily` values in `initializeState`. This makes sense because the `atomFamily` atoms are created dynamically, and in my case are created based on the value of an atom.

<img src="https://user-images.githubusercontent.com/39128232/97140277-e620a680-1764-11eb-9815-9082a4ebde85.png" width="400" />

I could set all atoms in `initializeState`, and then try to set the `atomFamily` values in a `useEffect`, but it doesn't feel like the `useEffect` would be guaranteed to run after all the `atomFamily` values have been initialized.

Is this a problem anyone has solved before? Could the `set` function in the `MutableSnapshot` possibly hold onto the value passed to it until the `atomFamily` atom is created?

**Comment by drarmstr** [comment]
Yes, `initializeState` prop for `<RecoilRoot>` goes global initialization.  The `get*` accessors in a `MutableSnapshot` don't reflect previous `set`'s in the transaction because they represent the value as of the start of the transaction and the `set`'s can be batched for performance.  Using the updater form of `set` by passing a callback allows you to get the current value of the atom based on `set`'s within that current transaction.

But, in general, using `initializeState` for state persistence can be awkward for working with dynamic atoms in a type-safe way.  It is also limiting because it's a global persistence policy for the entire `<RecoilRoot>`.  The plan for state persistence of atoms is to use Atom Effects for state serialization.  This allows us to specify state persistence policy per-atom in a type-safe, co-locate the policy with atom definition, and compose multiple persistence or state synchronization policies.  We haven't updated the documentation yet for these, but you can check out an example in #591 and enabled for `atomFamily()` in #449

**Comment by drarmstr** [comment]
Added documentation in #680
