### ISSUE TITLE
[Immer.js] Pattern for working with Map

### ISSUE THREAD

**Issue by jkavalec** [facebookexperimental/Recoil#723]
I want to migrate to Recoil,

all collection based examples have classic immutable array update pattern, however I want to update JS/TS Map<K,V> object (I would prefer not to use normal JS object {}). Is there any Recoil way to do this thing?

If I use Immer for this wont it conflict with Recoil inner workings somehow?

**Comment by drarmstr** [comment]
It is important to not mutate objects or values that are stored in Recoil state.  There are some exceptions to this, but basically all state changes need to be observed by Recoil using a provided mechanism (such as a `useRecoilState()` setter) so that Recoil is aware of the change and can update subscribing selectors and React components.  Because of this Recoil will attempt to freeze any stored values in development mode in order to help catch bugs where stored values are mutated.

I haven't used `Immer.js`, but from looking at it quickly it appears to be a library for providing immutable objects based on built-in JS objects.  So, it sounds like it would be compatible with storing the frozen `Immer.js` objects as Recoil values.
