### ISSUE TITLE
[Documentation]: Minor error in the documentation

### ISSUE THREAD

**Issue by nickmarca** [facebookexperimental/Recoil#741]
Hello, 
I'd like just to report a minor error in the documentation at this [page](https://recoiljs.org/docs/basic-tutorial/atoms):
As you can see on the screenshot, on the `TodoItemCreator` component we should have:
`const [,setTodoList] = useRecoilState(todoListState);`
instead of
`const setTodoList = useRecoilState(todoListState);`

I know it's obvious for most of us, but beginners might go crazy with that.

<img width="808" alt="Screenshot 2020-11-14 at 18 33 34" src="https://user-images.githubusercontent.com/3733116/99154529-7b4df580-26a8-11eb-819a-a896cbdbf39e.png">

Thanks.

**Comment by lucsky** [comment]
@nickmarca Look closer: this code sample uses `useSetRecoilState`, not `useRecoilState`, so it looks correct to me.

**Comment by drarmstr** [comment]
@nickmarca - An important reason one might use [`useSetRecoilState()`](https://recoiljs.org/docs/api-reference/core/useSetRecoilState/) instead of [`useRecoilState()`](https://recoiljs.org/docs/api-reference/core/useRecoilState) is if you want to avoid a component subscribing to re-render when the value is changed.
