### ISSUE TITLE
Selector does not re-evaluate when state changes to previous value

### ISSUE THREAD

**Issue by Khachatour** [facebookexperimental/Recoil#747]
Hey there dear Recoil team!

I have an issue regarding selector re-evaluation, my scenario is the following.

I have an pagination component and whenever I change the `currenPage` selector re-evaluates until I finish every page click, after that whenever I click on the for example previous page, selector does not evaluate.

```js

const pageQuerySelector = selector({
  key: 'pageQuerySelector',
  get: ({ get }) =>
    Number(get(filterTermsFromQuery)[QUERY_SELECTORS.PAGE]) || 1,
});

const phonePaginationState = atom({
  key: 'phonePaginationState',
  default: pageQuerySelector,
});

const pageSelector = selector({
  key: 'pageSelector',
  get: ({ get }) => {
    // If I have 3 pages, this log works only 3 times
    console.log('pageSelector');

    return get(phonePaginationState);
  },
});

```

**Comment by drarmstr** [comment]
Selectors implement a cache as an optimization to avoid re-evaluations.  So, it is expected behavior that going back to a previous state will cause the cached selector value to be used instead of re-evaluating.  This is one reason why selector evaluation functions should not have side-effects and must be "idempotent," returning the same value for a given set of inputs and dependent state.

**Comment by Khachatour** [comment]
Thanks a lot for the explanation!
