### ISSUE TITLE
snapshots observing 

### ISSUE THREAD

**Issue by mahmoud-ezzat-va** [facebookexperimental/Recoil#751]
I have used the time travel example here
https://recoiljs.org/docs/guides/dev-tools#time-travel

I have some atoms that have a high rate of state update at some points in times

and I am storing the snapshots for time-traveling but these highly dynamic atoms pollute my history stack

the state of the atom I have contained
`{
  id,
  type: 'square',
  attributes: {
    positionX: Math.random() * 500,
    positionY: Math.random() * 400 - 200,
    scaleX: 1,
    scaleY: 1,
    width: 180,
    height: 80,
    color: '#f05454',
    label: 'square',
    offsetX: 0,
    offsetY: 0,
  },
}`

i don't want to store the snapshots when any of  postionX and postionY changes

**Comment by drarmstr** [comment]
Using Snapshots for time travel is useful for dev tools.  But, as you have seen, it may not be appropriate for application logic since it is notified for all state changes.  Consider [atom effects](https://recoiljs.org/docs/guides/atom-effects#history-example) for setting up observers to subscribe to changes in specific atoms.
