### ISSUE TITLE
Atom effect cleanup hasn't been fired

### ISSUE THREAD

**Issue by suren-atoyan** [facebookexperimental/Recoil#806]
Could you please check [this](https://codesandbox.io/s/recoil-jdngb?file=/src/App.js) code snippet?

I guess the cleanup function on `atom/atomFamily` doesn't work correctly. It hasn't been fired either when you change the params of `atomFamiliy` or you totally unmount the component that uses that particular `atom/atomFamily`.

**Comment by drarmstr** [comment]
Atom Effect cleanup is executed when an atom goes out of scope and is released.  Currently this only happens when the `<RecoilRoot>` itself is unmounted.  (Note that the atom maintains its state even when components using it are unmounted)  In the future as garbage collection of atoms is introduced there may be other situations atoms are released and cleanup handlers executed.
