### ISSUE TITLE
selector not being called after error

### ISSUE THREAD

**Issue by guerrap** [facebookexperimental/Recoil#813]
I took an example from the docs and edited a bit to reproduce the behavior. In the code, a selector makes an async query that causes it to throw an error.

https://codesandbox.io/s/stoic-hooks-k7je8?file=/src/App.js:859-872

Current behavior:
After the error the selector is no more called, there's no `Called` log in the console after multiple click events on the button.

Expected behavior:
The selector is called every time the button is clicked because the `CurrentUserID` is updated each time, and the logs are displayed in the console.

Is this the correct and thus expected behavior? Am I missing something?

**Comment by drarmstr** [comment]
This is because your `<ErrorBoundary>` catches the error and then goes into an error state which no longer renders the children.  When it doesn't render the children there is nothing trying to execute the `currentUserNameQuery` with the new user ID.  If you want to try again you would need to add some mechanism to reset your `<ErrorBoundary>` out of the error state.

This example adds a component using the `currentUserNameQuery` outside of an `<ErrorBoundary>` to demonstrate that pressing the button changes the ID and issues a new query: https://codesandbox.io/s/determined-jennings-n0dem?file=/src/App.js:1036-1063
