### ISSUE TITLE
expose "get" on useRecoilCallback

### ISSUE THREAD

**Issue by salvoravida** [facebookexperimental/Recoil#829]
Hi folks, i'm using useRecoilCallback for running tasks.

it may be needed during a task to get the last updated value of an atom

why not espose the "get" function ?

```javascript
function get(recoilState) {
      return getRecoilValueAsLoadable(storeRef.current, recoilState);
    }
```

i'm currently use a fake get (that i suppose is safe because enqueue updaters) that is OK.

```javascript
const counter = atom({
  key: "counter",
  default: 0,
});

const injectGet = (set) => (recoilState) => {
  return new Promise((resolve) => {
    set(recoilState, (prev: unknown) => {
      resolve(prev);  //TODO handle lodables
      return prev;
    });
  });
};

export const useTestTask = () =>
  useRecoilCallback(({ snapshot, set}) => async () => {
      const get = injectGet(set);
      for (let i = 0; i < 20; i++) {
        let current = await get(counter);
        let old = await snapshot.getLoadable(counter).toPromise();
        console.log("current, old ", current, old);
        set(counter, inc);
      }
    },
    []
  );
```

But there is a problem if i want to read from async selectors:

```javascript
const counterSelector= selector({
    key:"counterSelector",
    get: async ({get})=> get(counter)
})

export const useTestTask2 = () =>
  useRecoilCallback(({ snapshot, set}) => async () => {
      const get = injectGet(set);
      for (let i = 0; i < 20; i++) {
        let current = await get(counterSelector);
        let old = await snapshot.getLoadable(counterSelector).toPromise();
        console.log("current, old ", current, old);
        set(counter, inc);
      }
    },
    []
  );

//"cannot set selector while it is pending...."
```

Patching useRecoilCallback and expose real get solve all the problems
```javascript
function useRecoilCallback<Args: $ReadOnlyArray<mixed>, Return>(
  fn: CallbackInterface => (...Args) => Return,
  deps?: $ReadOnlyArray<mixed>,
): (...Args) => Return {
  const storeRef = useStoreRef();
  const gotoSnapshot = useGotoRecoilSnapshot();

  return useCallback(
    (...args): Return => {
      // Use currentTree for the snapshot to show the currently committed state
      const snapshot = cloneSnapshot(storeRef.current);

      function set<T>(
        recoilState: RecoilState<T>,
        newValueOrUpdater: (T => T) | T,
      ) {
        setRecoilValue(storeRef.current, recoilState, newValueOrUpdater);
      }

      function reset<T>(recoilState: RecoilState<T>) {
        setRecoilValue(storeRef.current, recoilState, DEFAULT_VALUE);
      }
    
///patch
     function get(recoilState) {
      return getRecoilValueAsLoadable(storeRef.current, recoilState);
    }


  /// ....
}
```

All ok now:
```javascript
export const useTestTask3 = () =>
  useRecoilCallback(({ snapshot, set, get}) => async () => {
      for (let i = 0; i < 20; i++) {
        let current = await get(counterSelector).toPromise();
        let old = await snapshot.getLoadable(counterSelector).toPromise();
        console.log("current, old ", current, old);
        set(counter, inc);
      }
    },
    []
  );
```

Any thoughts?

**Comment by salvoravida** [comment]
@drarmstr i understand that you would be clear to developers that getting current value is something to handle with care,  but i think it's a very useful feature on useRecoilCallback. maybe it could be called "dangerouslyGetCurrent" for beginners care.

**Comment by drarmstr** [comment]
We don't want to expose a `get` for the "current" state directly in `useRecoilCallback()` due to the risk of tearing, which can lead to hard-to-debug user bugs.  For example, if a user gets the "current" state of atom A in a Recoil callback, then awaits, then gets the "current" state of atom B it may be that atom A has changed in the meantime and thus the callback now has an invalid combination of states for atoms A and B in the closure.

As you point out, the updater form of setting an atom can be used to observe the "current" value when updating an atom to a new value.  It's not intended to use this to read values and hacks to do so will cause unnecessary atom/selector updates and component re-renders.

If an advanced user understands these risks, it is possible for them to create a callback to get the "current" state.  For example, a callback to get state could be constructed as follows:
```jsx
const getPromise = useRecoilCallback(({getPromise}) => getPromise);
```
This callback can, in turn, then be used by other callbacks.

**Comment by salvoravida** [comment]
i@drarmstr i understand your motivation, but i'm very happy that there is a way to get current state while running tasks, if needed in advanced tasks. (like redux-saga does) Because it would be a limitation for the great power of recoil!
Thank you!

**Comment by sstur** [comment]
> If an advanced user understands these risks, it is possible for them to create a callback to get the "current" state. For example, a callback to get state could be constructed as follows

Just to be clear, this will produce an async getter, effectively returning a promise that must either be await'd or then'd.

There are certainly use cases where we can't await, and overall seems especially strange considering the data is in memory, why should we need to use async patterns to get data from memory.

On the other hand I also feel dirty abusing the set as a get as mentioned by the OP, so I'm wondering if there is any synchronous way to read a value from an atom (atom family in my case) on demand, aka not using `useRecoilValue` (because useRecoilValue implicitly subscribes my component to changes in the value, resulting in re-renders, among other tradeoffs).

Any other way?

**Comment by BenjaBobs** [comment]
If you understand the implications you can use the work-around I mentioned here: https://github.com/facebookexperimental/Recoil/issues/289 
It'll get you a loadable, which has the `.valueMaybe()` accessor, which you can use to synchronously get the value (if it exists), and otherwise `void`.

**Comment by sstur** [comment]
Wow, thanks @BenjaBobs, that's exactly what I was after! I should have realized that `snapshot` has a `getLoadable()` method.

For reference, here's what I ended up with:

![image](https://user-images.githubusercontent.com/369384/110354507-19195780-7fed-11eb-9eca-d5387d360988.png)
