### ISSUE TITLE
useGotoRecoilSnapshot not working

### ISSUE THREAD

**Issue by mog3n** [facebookexperimental/Recoil#840]
Hi, might be user error. I have a component called `<RecoilPersist />` that i append as a child to the render tree.

```
function RecoilPersist(props: any) {
        // Initialize state
        const snapshot = useRecoilSnapshot();
        const gotoSnapshot = useGotoRecoilSnapshot();

        useEffect(() => {
            const atoms = [restaurantEndpointState];
            const data = JSON.parse(persistData);

            const getDataFromPersistingObject = (_data: any, _key: string) => {
                const arr = Object.values(_data);
                const data = arr.filter((atomData: any) => {
                    return atomData.atom.key === _key;
                });
                return data.length > 0 ? (data[0] as any).data : {};
            };

            async function hydateRecoil() {
                snapshot.asyncMap((mutableSnapshot) => {
                    return new Promise((resolve, reject) => {
                        const { set } = mutableSnapshot;
                        atoms.forEach((atom) => {
                            try {
                                const atomData = getDataFromPersistingObject(data, atom.key);
                                console.log(atom, atomData);
                                set(atom, atomData);
                            } catch (e) {
                                console.error(e);
                            }
                        });
                        resolve();
                    });
                });
                gotoSnapshot(snapshot);
            }

            hydateRecoil();
        }, []);
```

It appears that the atoms are loading properly. I'm getting the right key and the right data. But when calling
```
useRecoilState(restaurantEndpointState)
```
It returns the default atom value.

**Comment by jonbnewman** [comment]
I think your `useEffect()` is missing the dependencies `snapshot` (and `gotoSnapshot`).

**Comment by algorithmhash** [comment]
You should initialize your method outside of use effect and call it like this:
```
hydrateRecoil(){
  ...
}

useEffect(()=>{
   hydrateRecoil();
},[hydrateRecoil])
```

**Comment by drarmstr** [comment]
Seems like you are getting a `snapshot` in this component's render and referencing it from your effect, but not including it in the effect's dependency list.  I gather the intention is to perform a one-time initialization so you don't want to include it in the dependencies for the hook.  But, this use of React hooks isn't recommended, check out the `exhaustive-deps` lint rule.  I also wouldn't recommend using `useRecoilSnapshot()` here since that will cause the component to subscribe and re-render for all state changes with a new snapshot; useful for dev tools but a waste if you just need it for one-time initialization.

If you want to initialize state via a snapshot, check out the [initializeState](https://recoiljs.org/docs/api-reference/core/Snapshot#state-initialization) prop for [`<RecoilRoot>`](https://recoiljs.org/docs/api-reference/core/RecoilRoot) (though this won't work with families).  For other ideas in implementing state persistence, check out the docs for [Atom Effects](https://recoiljs.org/docs/guides/atom-effects).
