### ISSUE TITLE
[question]  immutable selector's value not working when the atom was changed

### ISSUE THREAD

**Issue by postbird** [facebookexperimental/Recoil#845]
Demo online: https://codesandbox.io/s/bold-voice-ii8kz?file=/src/App.js

I use an immutable Map in selector to prevent re-render (there return the same Map instance each time):

```javascript
// record the Map of each selector's return
const statsList = [];

let immutableStats = ImmutableMap({ all: 0, active: 0, completed: 0 });

const todosState = atom({
	key: uuidv4(),
	default: [],
});

const todoStats = selector({
	key: uuidv4(),
	get: ({ get }) => {
		statsList.push(immutableStats);
		// get(todosState) but return the same immutable Map instance
		const todos = get(todosState);
		return immutableStats;
	},
});
```
when I used `todoStats` in Component, component will be re-rendered each time:
```jsx
const Stats = () => {
	const stats = useRecoilValue(todoStats);
	console.log(statsList.map(item => item === stats));
	return (
		<ul style={{ textAlign: 'center' }}>
			<li>ALL: {stats.get('all')}</li>
			<li>ACTIVE: {stats.get('active')}</li>
			<li>COMPLETED: {stats.get('completed')}</li>
		</ul>
	);
};
```
it is not working when the atom `todosState` was changed, even all the  Immutable Map are same,.

![GIF](https://user-images.githubusercontent.com/16200574/105218019-9a2ca480-5b8f-11eb-96fb-b0a6458dddda.gif)

- Q1:
  - If the value of an atom has changed, selectors that rely on this atom will force re-render every time. Is this as expected?
- Q2:
  - Is there any way to avoid this problem?

**Comment by drarmstr** [comment]
Your example looks strange because `todoStats` is always returning the same constant `immutableStats` object, with values of 0.  That's why the numbers always say 0.  It's also problematic because your `todoStats`'s `get()` property has a side-effect of pushing on `statsList`.  Selector `get()` methods should not have side-effects.  In this example it doesn't look like that array is ever read, so it doesn't matter, but it is problematic since side-effects can represent state changes that Recoil is unaware of and thus not able to properly re-render components to reflect.

It is currently expected that any update to a selector's dependencies will cause a re-render for components subscribing to that selector, even if the value is the same.  There is a pending optimization #749 that will avoid re-rendering when selectors produce the same value via reference equality, however that feature flag has not been enabled for OSS just yet.
