### ISSUE TITLE
Atom is not re-rendering on update of value across components

### ISSUE THREAD

**Issue by aaely** [facebookexperimental/Recoil#864]
Cart Component:
```

export default function Cart() {
    const _cart = useRecoilValue(cart)

    return(
        <div>
            <h3>Shopping Cart</h3>
            <Table striped responsive>
                <thead>
                    <tr>
                        <th>
                            Item #
                        </th>
                        <th>
                            Product Name
                        </th>
                        <th>
                            Product Cost
                        </th>
                        <th>
                            Product Quantity
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {cart.length > 0 && cart.map((item, index) => {
                        console.log(item)
                        return(
                            <tr key={item.id}>
                                <td>
                                    {index + 1}
                                </td>
                                <td>
                                    {item.name}
                                </td>
                                <td>
                                    {item.cost}
                                </td>
                                <td>
                                    {item.quantity}
                                </td>
                            </tr>
                        )
                    })}
                </tbody>
            </Table>
        </div>
    )
}
```
Product List Component:

```
export default function Test4 () {
    const account = useRecoilValue(address)
    const [handle,setHandle] = useRecoilState(itemHandle)
    const [_cart, setCart] = useRecoilState(cart)
    const product = useRecoilValue(getProduct)
    
    const addToCart = (data) => {
        const index = cart.findIndex(x => x.id === data['_id'])
        console.log(index)
        const newItem = [{ id: data['_id'], name: data['product/name'], cost: data['product/cost'], quantity: 1}]
        if(index < 0 && cart.length === 0) {
            console.log('first item')
            setCart(newItem)
        }
        if(index < 0 && cart.length >= 1) {
            console.log('new item')
            setCart([...cart, newItem])
        }
        if(index >= 0) {
            console.log('increment quantity')
            let newCart = cart
            newCart[index].quantity = newCart[index].quantity + 1
            console.log(newCart)
            setCart(newCart)
        }
    }

    useEffect(() => {
        setHandle('product_PineappleExpress')
    }, [])

    return(
        <div className='App'>
            Product: <br /> {product.length > 0 && product.map(a => {
                console.log(a)
                return(
                    <p key={a['_id']} >
                        {a['product/name']}  {a['product/cost']} <Button color='success' onClick={() => addToCart(a)}>Add To Cart</Button>
                    </p>
                )
            })}
        </div>
    )
}
```
The cart rerenders without issue upon adding the first item, or a new item; however, it does not rerender when incrementing the quantity. If I change something in the text editor and cause a hot reload, the value displays correctly. Why is this not rerendering in this situation? I was certain I was doing something wrong, but after seeing the update every time after a hot reload I am at a loss. I am attaching a screenshot of the devtools showing the incrementing value off to the right.
![Screenshot from 2021-01-30 21-38-14](https://user-images.githubusercontent.com/40217979/106375731-90e7c880-6343-11eb-9388-6a1739e4c5ff.png)

**Update**

So by adding in:

setCart([])

before setting the new values, it seems to update correctly. Im curious why this is the case... I wonder why it doesn't detect the change if the length of the array doesn't change?

**Comment by yokunjon** [comment]
This is related to how React works. React uses Object.is method to compare between the previous state and updated, if no change occurs, it doesn't render anything. So, when you do ``setCart(newItem)``, you create a new àrray object because of this line ``const newItem = [{ id: data['_id'], name: data['product/name'], cost: data['product/cost'], quantity: 1}]``. When you do ``setCart([...cart, newItem])``, you spread cart array into an empty array, append newItem to it. These both result in new objects, so React can detect changes and render accordingly. But, it isn't the case with ``setCart(newCart)`` because ``let newCart = cart`` doesn't change the object itself, only assigns another variable to the same object.

Because of this, React depends on immutability. Changing ``let newCart = cart`` into ``let newCart = [...cart]`` would work with this simple, flat data type. But it might result in a mess over-time. So, consider using https://github.com/immerjs/immer or https://github.com/kolodny/immutability-helper when you feel comfortable.
