### ISSUE TITLE
Optimizing for for loop within selector

### ISSUE THREAD

**Issue by tonyabracadabra** [facebookexperimental/Recoil#900]
I am having an spreadsheet application where I've made each cell an atom state, when feeding the data to the spreadsheet component, what I've been doing is using a `recordsSelector`

```ts
export type CellQuery = {
  recordId: string
  fieldId: string
};

export const cellsState = atomFamily<CellValue, CellQuery>({
  key: 'cell-states',
  default: null,
});

export const fieldIdsState = atom<string[]>({
  key: 'field-ids-state', 
  default: []
});

export const recordIdsState = atom({
  key: 'record-ids-state',
  default: []
});

export const recordsSelector = selector({
  key: 'records-selector',
  get: ({get}) => {
    const recordIds = get(recordIdsState) || [];
    const fieldIds = get(fieldIdsState) || [];

    return recordIds.map(recordId => {
      return fieldIds.reduce((value, fieldId) => {
        value[fieldId] = get(cellsState({
          recordId,
          fieldId
        }));

        return value
      }, { id: recordId });
    }, {}).concat({id: ''});
  }
})
```

However when I have just a little bit of more rows (say 1000 rows), I found that the time took by `recordsSelector` is astonishing 

![image](https://user-images.githubusercontent.com/6690727/109212677-b14d4c00-7764-11eb-91dd-3758baaa1f09.png)

I am wondering if there is anyways I can make it much much faster? It is taking me 100s just for get the value of all 14000 atom states.

**Comment by anc95** [comment]
I have made a demo on codesanbox to reproduce the performance issue, check [recoil select demo](https://codesandbox.io/s/recoil-selector-performance-hqcle).

**Comment by DeepAnchor** [comment]
I think the problem is that you're calling `set(cellState, cell.value)` inside a loop in your `useSetTableData` hook. This causes your `recordsSelector` to recompute its output every time any `cellState` changes since it's dependent on every upstream `cellState`. Every time `recordsSelector` gets recomputed, your table component has to re-render.

Probably what you'd want to do (instead of having one selector feed data to your entire table) is to is feed each cell its unique ID and have each cell grab its own state. If you have cells which rely on each others' states (like in a typical spreadsheet app), you can grab those upstream states directly from inside those cells.

**Comment by tonyabracadabra** [comment]
I wanted to reopen this issue and relate this to this issue https://github.com/facebookexperimental/Recoil/issues/914, I am wondering if there is any known issue for the poor performance with selector in combination with for loops? I love recoil but with this it is really hard to put it into production.
