### ISSUE TITLE
React has detected a change in the order of Hooks called by Component.

### ISSUE THREAD

**Issue by nxz91** [facebookexperimental/Recoil#921]
Related to the experiment of moving to Recoil, we're seeing the above error message next to a `Cannot assign to read only property` error message. What we're doing is basically this:

```
const setState = useSetRecoilState(someAtomWithMutability)
useEffect(() => {
  setState(s => {
    s.close()
    return null
  })
}, [])
```

The atom is mutable and s.close() is mutating in some way. That seems to cause issues.

**Comment by BenjaBobs** [comment]
You have to explicitly enable mutability on the atom with `dangerouslyAllowMutability`: https://recoiljs.org/docs/api-reference/core/atom
But for most cases I find that mutable data (such as typescript classes) is best stored outside of Recoil.

**Comment by nxz91** [comment]
The atom is already mutable (dangerouslyAllowMutability: true)

**Comment by BenjaBobs** [comment]
Assuming `s` is some kind of connnection or short lived object, I don't think it's a good idea to put that directly in recoil state.
I would instead have an external object that manages `s`, and then store whatever data `s` produces in recoil state.

**Comment by drarmstr** [comment]
It may also be a better practice to store some ID that can then reference `s`, rather than `s` directly.  

Though, I wonder if this is a red herring for the error message about React detecting a change in hook order.  That error message shows up when React hooks are used incorrectly such as being called conditionally, in a loop, etc.  That can sometimes happen in unobvious ways.  For example, the most recent I saw it was when some React components were provided in a config but was being rendered by calling it as a normal function versus as a JSX component, so React didn't treat them as different components and thus threw this error when the configuration changed.

**Comment by nxz91** [comment]
Thank you both for the feedback. Storing the ID to s rather than s directly makes sense, but makes moving from the context API to Recoil a little harder of course.

It turns out that we were actually calling hooks in the wrong order somewhere and after that this error message did not crop up again and I cannot tell now for sure whether it has to do with us not calling .close() in the updater function anymore.

**Comment by RPisRyan** [comment]
A note for anyone else who encounters 'React has detected a change in the order of Hooks':
You will get this error when you accidentally use a React hook inside of Recoil code (such as in selector `get` implementation). It's easy to use `useRecoilValue()` when you should be doing `get()`.
The linter should be picking this up, but mine isn't.
