### ISSUE TITLE
Data using useRecoilState caused the following issues.

### ISSUE THREAD

**Issue by mingiki** [facebookexperimental/Recoil#941]
Hello

Data using useRecoilState caused the following issues.

' TypeError: Cannot add property 0, object is not extensible '

Is there any way I can fix it?

**Comment by BenjaBobs** [comment]
By default Recoil state is not mutable.
You can enable mutability in the setup of the atom: https://recoiljs.org/docs/api-reference/core/atom
However this is not recommended. The recommended way is to create a new object with the new state you want to save.
The reason is that Recoil can then check the references, and will see that it's a different reference, and then knows to tell all subscribers to that state to update because the state has a new value.
If you use mutable state, you will have to manually update each place you use the data.

**Comment by mingiki** [comment]
thanks bro :)
