### ISSUE TITLE
[Question] Is there a way to handle errors with ErrorBoundary when posting data with Recoil?

### ISSUE THREAD

**Issue by lars-jpeg** [facebookexperimental/Recoil#964]
I was able to trigger react's ErrorBoundary with an error thrown in an async get in a selector. However I would like to POST data with Recoil and potentially catch error's from the POST request with an ErrorBoundary - if that's possible.

https://github.com/facebookexperimental/Recoil/issues/462

From this thread I saw that useRecoilCallback was suggested to post data, however errors thrown inside it aren't caught by ErrorBoundary because the api calls require async - await.

Currently async set selectors don't work either.

There is the possibility of POSTing data with a get selector, but I would need it to trigger only when I click a 'Save' button on the UI.

Is there a clean pattern to this or is it possible to catch POST request errors with React's ErrorBoundary?

**Comment by davidmccabe** [comment]
It's not recommended to POST using Recoil, because Recoil's async selectors are only intended for retrieving time-invariant data, which means it can be treated as if purely functional. Instead, POST via event handlers or effects.

**Comment by davidmccabe** [comment]
It's not recommended to POST using Recoil, because Recoil's async selectors are only intended for retrieving time-invariant data, which means it can be treated as if purely functional. Instead, POST via event handlers or effects.

ErrorBoundary is only used for catching errors during React rendering. Errors in event handlers (including useRecoilCallback) should be caught and result in some state change that handles the error -- see here for an example: https://reactjs.org/docs/error-boundaries.html#how-about-event-handlers

**Comment by drarmstr** [comment]
@lars-jpeg - For bi-directional syncing, you can also try [atom effects](https://recoiljs.org/docs/guides/atom-effects#write-through-cache-example) to use an atom as a local write-through cache.  As Dave mentions, you should handle the try/catch directly in the effect.

**Comment by iahu** [comment]
how to globally throw a error ? in some reason, i want to throw a error if any request response a special data to recoil selector.
