### ISSUE TITLE
Ability to clear selector caches

### ISSUE THREAD

**Issue by trentmwillis** [facebookexperimental/Recoil#972]
Hi there, we have an app using `v0.1.2` of Recoil and tried today to upgrade to `v0.2.0` but ran into an issue. It seems that atom state is being shared across different instances of `RecoilRoot` which makes it difficult to test certain types of `default` values.

For example, we have an `atomFamily` that derives the default values based on URL params. In our tests, we set up the URL state and then access the `atomFamily`. With this caching we are now seeing, this means that only the first test works properly as the subsequent tests do not actually retrieve the value from the URL.

[Here is a simplified reproduction for clarity.](https://codesandbox.io/s/recoil-cache-test-issue-93tgp?file=/src/my-atom-family.test.js)

I know in [the documentation there is note about this](https://recoiljs.org/docs/api-reference/core/RecoilRoot):

> Note that caches, such as selector caches, may be shared across roots.

But you'll note in the reproduction above, that even using `reset()` doesn't appear to invalidate the cache. (I also tried using `key`, but that yielded the same results.)

Is this intended behavior? If so, what would be the recommended approach to fixing this? Is there some method to clear the Recoil caches or force the RecoilRoot to not use the cache?

Thanks in advance for your help!

**Comment by getsaf** [comment]
This is absolutely crushing me in my testing right now. I've tried all kinds of work-arounds to reset the recoil state but I can't get it to reset.

The end result is that **data bleeds between tests** so tests do not start with a clean slate. The resulting errors are pretty obscure and case dependent and debugging it to the point where I found the issue is recoil bleed took a while.

My only workaround so far is to do strange things in my tests like changing values unnecessarily to trigger updates which I can't in good conscience commit.

Just to add some info, I've tried:

* `renderHook` testing (as in OP's example)
* `snapshot_UNSTABLE` testing (per the Recoil docs)
* Created a wrapper component that uses `useGotoSnapshot` to attempt to reset to a known initial clean slate

All have failed.

**Comment by drarmstr** [comment]
Looking at your example reproducer let me try to clarify the issue:  The `atomFamily()` has a parameterized default.  This function establishes the default for an atom value on first usage.  That first usage is cached across all `<RecoilRoot>`'s as it is a cache.  Resetting the atom doesn't cause the default to be re-evaluated.
If that is the issue, then I think this is as expected since reset only resets the actual atom state, not cached default values.  Default values are intended to be static.  Though, this does raise a usability concern for families with parameterized defaults, particularly as garbage collection is introduced which may cause dynamic release and re-initialization of atoms.
Anyway, for your use-cases, perhaps [this pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries#query-default-atom-values) is more of what you are looking for to use a selector as a default for the atom to support dynamic defaults.  You can also use `selectorFamily()` as a default for `atomFamily()`

**Comment by getsaf** [comment]
@drarmstr Thanks for the reply.

> That first usage is cached across all <RecoilRoot>'s as it is a cache. Resetting the atom doesn't cause the default to be re-evaluated.

This indeed seems to be the issue that causes data bleed between tests. To add some information here, the issue is not necessarily related to first-usage and is also not exclusive to `atomFamily`, but it also affects plain selectors that depend on plain atoms.

I have modified @trentmwillis example with a [simple atom/selector scenario](https://codesandbox.io/s/recoil-cache-test-issue-forked-wrb1z?file=/src/my-atom-family.test.js). The key seems to be that we are depending on external data that only affects the selector value when the atom dependency changes. In this scenario, simply having two tests that assign the same state to an ATOM will cause the selector to use cache from a previous test.

I tried using Jest's [`resetModules`](https://jestjs.io/docs/configuration#resetmodules-boolean) to fix it but had no luck.

I'm basically using [this pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries/#use-a-request-id) from your suggestion, but I am trying to make expectations on initial state which is failing between tests due to bleed from prior tests.

```ts
import { atom, selector, snapshot_UNSTABLE } from "recoil";

let testNumber = 0;
const messageState = atom({
  key: "test:message",
  default: "my default message"
});

const numberedMessageState = selector({
  key: "test:upperMessage",
  get: (o) => {
    const message = o.get(messageState);
    return `${message} ${testNumber}`;
  }
});

describe("recoil cache bleed", () => {
  it("works just fine for the first test", async () => {
    testNumber = 1;
    const snapshot = snapshot_UNSTABLE((s) =>
      s.set(messageState, "test message")
    );
    const numberedMessage = await snapshot.getPromise(numberedMessageState);
    expect(numberedMessage).toBe("test message 1");
  });

  it("the second test uses the same messageState but does not get the testNumber correct because it is cached from the first test", async () => {
    testNumber = 2;
    const snapshot = snapshot_UNSTABLE((s) =>
      s.set(messageState, "test message")
    );
    const numberedMessage = await snapshot.getPromise(numberedMessageState);
    expect(numberedMessage).toBe("test message 2");
  });
});
```

It seems that the selector is just not starting from a clean-slate so the side-effect that we are depending on in the initial load state is cached and re-used in subsequent tests.

If anyone is interested, here is my hack to work-around this issue until a proper fix in Recoil comes along. I'm basically injecting a dependency on a cache-busting increment for every selector that is created (note, I did not account for selectorFamily yet):

```ts
import * as recoil from 'recoil';
const actualRecoil: typeof recoil = jest.requireActual('recoil');
let increment = 0;
const testCacheBuster = actualRecoil.atom({
  key: 'test:increment',
  default: increment
});

jest.mock('recoil', () => ({
  ...actualRecoil,
  snapshot_UNSTABLE: (initState?: (snapshot: recoil.MutableSnapshot) => void) => {
    return actualRecoil.snapshot_UNSTABLE(s => {
      s.set(testCacheBuster, ++increment);
      initState?.(s);
    });
  },
  selector: (config: any) => {
    return actualRecoil.selector({
      ...config,
      get: config.get
        ? o => {
            o.get(testCacheBuster);
            return config.get(o);
          }
        : undefined
    });
  },
  RecoilRoot: new Proxy(actualRecoil.RecoilRoot, {
    apply: (target, thisArg, [props, context]) =>
      target.apply(thisArg, [
        {
          ...props,
          initializeState: s => {
            s.set(testCacheBuster, ++increment);
            props.initializeState?.(s);
          }
        },
        context
      ])
  })
}));
```

Also, for posterity, I placed this test in my app so that when the bug is fixed, we'll be notified to remove the above hack from our codebase:
```ts
import * as recoilTypes from 'recoil';
const { atom, selector, snapshot_UNSTABLE } = jest.requireActual('recoil') as typeof recoilTypes;

let testNumber = 0;
const messageState = atom({
  key: 'test:message',
  default: 'my default message'
});

const numberedMessageState = selector({
  key: 'test:upperMessage',
  get: o => {
    const message = o.get(messageState);
    return `${message} ${testNumber}`;
  }
});

describe('bug in recoil', () => {
  it('works just fine for the first test', async () => {
    testNumber = 1;
    const snapshot = snapshot_UNSTABLE();
    const numberedMessage = await snapshot.getPromise(numberedMessageState);
    expect(numberedMessage).toBe('test message 1');
  });

  it('blah', async () => {
    testNumber = 2;
    const snapshot = snapshot_UNSTABLE();
    const numberedMessage = await snapshot.getPromise(numberedMessageState);
    expect(numberedMessage).toBe('test message 2');
  });

  it('the second test uses the same messageState but does not get the testNumber correct because it is cached from the first test', async () => {
    testNumber = 2;
    const snapshot = snapshot_UNSTABLE(s => s.set(messageState, 'test message'));
    const numberedMessage = await snapshot.getPromise(numberedMessageState);
    expect(() => {
      if (numberedMessage === 'test message 2') {
        // It works correctly now!!!!
        throw new Error(`
          It looks like you have updated Recoil which fixed a bug in selector
          caching. This means we should remove the hack that was working around
          the bug and use pure Recoil.

          Please remove this entire test file and the recoil hack in the setupTests.js
          file. All tests should continue to pass once the hack is removed.
      `);
      }
    }).not.toThrow();
  });
});
```

**Comment by trentmwillis** [comment]
Thanks for the response @drarmstr. However, like @getsaf, the suggested pattern doesn't fix the core issue as the initial default value is still used across multiple tests.

You confirmed my assumption that `reset()` does _not_ reset the cached default values, so the issue then is _how_ would you reset cached default values?

Based on [the example in the guide you shared](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-default-atom-values), it seems like non-static, default values are a use case that is intended to be supported. If that is the case, some documented method of resetting the default value would be very helpful for testing.

If this requires a new feature or some other change, I'd be happy to help contribute it.

**Comment by drarmstr** [comment]
Reset is reseting to the default value, it's just the default value is determined at first-use for families.  This will change with garbage collection.  The example guide for [dynamic defaults](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-default-atom-values) discusses using a selector for dynamic defaults, which can change.  If the selector for the default has no dependencies, though, it will never update or reset.  You can also use [this pattern](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-refresh) for refreshing selectors.

If we're just talking about testing use-cases, though, then it may also be appropriate to use `jest.resetModules()` to just clear everything.  We do this for Recoil unit tests in [`Recoil_TestingUtils.js`](https://github.com/facebookexperimental/Recoil/blob/master/src/testing/Recoil_TestingUtils.js#L252)  (see #1019)

**Comment by getsaf** [comment]
I believe this is strictly about testing. `jest.resetModules()` does not fix this issue.

May I suggest pasting [this test case](https://codesandbox.io/s/recoil-cache-test-issue-forked-wrb1z?file=/src/my-atom-family.test.js) file into a local repo to see what we are seeing?

I don't mind creating an entire git repo you can clone and run to see the issue if it helps. I wish I could better follow the Recoil Repo myself or I'd take a stab at a fix :-/

**Comment by getsaf** [comment]
Just adding more information here. I dug a little deeper into Recoil's use of `jest.resetModules()` and I noticed that, `jest.resetModules()` is being used in combination with [this rather complex test-setup](https://github.com/facebookexperimental/Recoil/blob/master/src/core/__tests__/Recoil_RecoilRoot-test.js#L14-L45) that re-requires modules for each test. I think something like this would solve this issue we are having but I couldn't possibly ask my team to add this kind of complexity to all their component tests so I'm still at a loss for how to handle this in our project.

@drarmstr I may have misunderstood your suggestion to use `jest.resetModules` to simply mean "reset modules before each test". Is the suggestion to copy this hand-rolled pattern and add this complexity for all tests that use Recoil?

**Comment by getsaf** [comment]
I have been able to track the issue down to [this cache object](https://github.com/facebookexperimental/Recoil/blob/master/src/recoil_values/Recoil_selector.js#L205) containing data from previous tests.

I can confirm that simply clearing out the cache fixes the issue but I had to modify the recoil-source to test this.

@drarmstr Could we get a way to clear all selector caches so we can reset them between tests?

**Comment by trentmwillis** [comment]
I tried using `jest.resetModules()` but it makes test setup much more complex because any module under test that imports `recoil` also needs to be reset and re-required each time.

That said, I took a look at some other issues and I think once https://github.com/facebookexperimental/Recoil/issues/981 is addressed, then this issue will also be addressed. That ticket will allow the selector cache to be cleared so if you follow the [dynamic default](https://recoiljs.org/docs/guides/asynchronous-data-queries/#query-default-atom-values) pattern using selectors, it should fix the problem (at least for my use case described above).

**Comment by sebinsua** [comment]
> I can confirm that simply clearing out the cache fixes the issue but I had to modify the recoil-source to test this.

I did the same thing, but then [began to get duplicate atom warnings](https://github.com/facebookexperimental/Recoil/blob/19ec20c9efd43d4966b0d15ebf5e56bc573b38a0/src/core/Recoil_Node.js#L114-L131). Not sure how to clean up other state without breaking everything...

**Comment by getsaf** [comment]
@sebinsua This is definitely not ideal but I ended up streamlining my hack to patch recoil to expose caches globally in my tests with this patch. Requires a bit of maintenance on each recoil upgrade until there's a built-in solution but this is bulletproof for now.

patches/recoil+0.3.0.patch
```diff
diff --git a/node_modules/recoil/cjs/recoil.js b/node_modules/recoil/cjs/recoil.js
index 65412ec..c3f87f0 100644
--- a/node_modules/recoil/cjs/recoil.js
+++ b/node_modules/recoil/cjs/recoil.js
@@ -5763,6 +5763,9 @@ function treeCacheFromPolicy({
 } = defaultPolicy) {
   const valueMapper = getValueMapper(equality);
   const treeCache = getTreeCache(eviction, maxSize, valueMapper);
+  if (process.env.NODE_ENV === 'test') {
+    window.__HACK_RECOIL_CACHES__.push(treeCache);
+  }
   return treeCache;
 }
 
```

In jest global test setup
```ts
declare global {
  var __HACK_RECOIL_CACHES__: any[];
}
global.__HACK_RECOIL_CACHES__ = [];
afterEach(() => {
  for (const cache of global.__HACK_RECOIL_CACHES__) {
    cache.clear();
  }
});
```

**Comment by sebinsua** [comment]
> @sebinsua This is definitely not ideal but I ended up streamlining my hack to patch recoil to expose caches globally in my tests with this patch. Requires a bit of maintenance on each recoil upgrade until there's a built-in solution but this is bulletproof for now.

Ah, I see. I'm doing something similar now, but exposing a `clearCache` function.

###### `patches/recoil+0.3.0.patch`

```diff
diff --git a/node_modules/recoil/cjs/recoil.js b/node_modules/recoil/cjs/recoil.js
index 65412ec..d57d365 100644
--- a/node_modules/recoil/cjs/recoil.js
+++ b/node_modules/recoil/cjs/recoil.js
@@ -7,6 +7,15 @@ function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'defau
 var reactDom = _interopDefault(require('react-dom'));
 var react = _interopDefault(require('react'));
 
+var caches = [];
+function clearCache() {
+  if (process.env.NODE_ENV !== 'test') {
+    console.error("The custom `clearCache` API we added into Recoil needs the NODE_ENV to be 'test'");
+    return;
+  }
+  caches.forEach(cache => cache.clear());
+}
+
 /**
  * Copyright (c) Facebook, Inc. and its affiliates.
  *
@@ -521,23 +530,25 @@ function recoilValuesForKeys(keys) {
 }
 
 function registerNode(node) {
-  if (nodes.has(node.key)) {
-    const message = `Duplicate atom key "${node.key}". This is a FATAL ERROR in
-      production. But it is safe to ignore this warning if it occurred because of
-      hot module replacement.`; // TODO Need to figure out if there is a standard/open-source equivalent to see if hot module replacement is happening:
-    // prettier-ignore
-    // @fb-only: if (__DEV__) {
-    // @fb-only: const isAcceptingUpdate = require('__debug').isAcceptingUpdate;
-    // prettier-ignore
-    // @fb-only: if (typeof isAcceptingUpdate !== 'function' || !isAcceptingUpdate()) {
-    // @fb-only: expectationViolation(message, 'recoil');
-    // @fb-only: }
-    // prettier-ignore
-    // @fb-only: } else {
-    // @fb-only: recoverableViolation(message, 'recoil');
-    // @fb-only: }
-
-    console.warn(message); // @oss-only
+  if (process.env.NODE_ENV !== 'test') {
+    if (nodes.has(node.key)) {
+      const message = `Duplicate atom key "${node.key}". This is a FATAL ERROR in
+        production. But it is safe to ignore this warning if it occurred because of
+        hot module replacement.`; // TODO Need to figure out if there is a standard/open-source equivalent to see if hot module replacement is happening:
+      // prettier-ignore
+      // @fb-only: if (__DEV__) {
+      // @fb-only: const isAcceptingUpdate = require('__debug').isAcceptingUpdate;
+      // prettier-ignore
+      // @fb-only: if (typeof isAcceptingUpdate !== 'function' || !isAcceptingUpdate()) {
+      // @fb-only: expectationViolation(message, 'recoil');
+      // @fb-only: }
+      // prettier-ignore
+      // @fb-only: } else {
+      // @fb-only: recoverableViolation(message, 'recoil');
+      // @fb-only: }
+  
+      console.warn(message); // @oss-only
+    }
   }
 
   nodes.set(node.key, node);
@@ -5763,6 +5774,9 @@ function treeCacheFromPolicy({
 } = defaultPolicy) {
   const valueMapper = getValueMapper(equality);
   const treeCache = getTreeCache(eviction, maxSize, valueMapper);
+  if (process.env.NODE_ENV === 'test') {
+    caches.push(treeCache);
+  }
   return treeCache;
 }
 
@@ -7099,6 +7113,9 @@ function cacheFromPolicy({
 } = defaultPolicy$1) {
   const valueMapper = getValueMapper$1(equality);
   const cache = getCache(eviction, maxSize, valueMapper);
+  if (process.env.NODE_ENV === 'test') {
+    caches.push(cache);
+  }
   return cache;
 }
 
@@ -7619,6 +7636,8 @@ const {
 } = Recoil_WaitFor;
 
 var Recoil_index = {
+  // Testing
+  clearCache: clearCache,
   // Types
   DefaultValue: DefaultValue$3,
   // Components
@@ -7666,6 +7685,7 @@ var Recoil_index = {
   // Snapshot Utils
   snapshot_UNSTABLE: freshSnapshot$2
 };
+var Recoil_index_0 = Recoil_index.clearCache;
 var Recoil_index_1 = Recoil_index.DefaultValue;
 var Recoil_index_2 = Recoil_index.RecoilRoot;
 var Recoil_index_3 = Recoil_index.useRecoilBridgeAcrossReactRoots_UNSTABLE;
@@ -7701,6 +7721,7 @@ var Recoil_index_32 = Recoil_index.batchUpdates;
 var Recoil_index_33 = Recoil_index.setBatcher;
 var Recoil_index_34 = Recoil_index.snapshot_UNSTABLE;
 
+exports.clearCache = Recoil_index_0;
 exports.DefaultValue = Recoil_index_1;
 exports.RecoilRoot = Recoil_index_2;
 exports.atom = Recoil_index_4;
diff --git a/node_modules/recoil/index.d.ts b/node_modules/recoil/index.d.ts
index 6434db1..f593886 100644
--- a/node_modules/recoil/index.d.ts
+++ b/node_modules/recoil/index.d.ts
@@ -386,3 +386,5 @@ export function waitForAllSettled<RecoilValues extends { [key: string]: RecoilVa
 /* eslint-enable @typescript-eslint/no-explicit-any */
 
 export function snapshot_UNSTABLE(initializeState?: (shapshot: MutableSnapshot) => void): Snapshot;
+
+export function clearCache(): void;
```

And within our codebase, we have this:

```js
afterEach(() => {
    // In `recoil@0.3.0`, some of the state is shared across different instances of `<RecoilRoot />`.
    // This causes tests to behave incorrectly, since our mocks are not picked up and caches from
    // previous tests are used.
    //
    // Until it has been fixed upstream, we've patched Recoil to support clearing its cache between tests.
    // See: https://github.com/facebookexperimental/Recoil/issues/972#issuecomment-841848081
    clearCache();
});
```

**Comment by florianbepunkt** [comment]
I saw that https://github.com/facebookexperimental/Recoil/issues/981 now add a caching strategy. Would it be possible to add a additional strategy of "none"? So caching would effectively be disabled? This would allow to disable caching in tests and solve this issue.

**Comment by drarmstr** [comment]
We are hesitant to expose a `none` option as selectors can be looked up a lot when checking on dependency state and we are wary of un-intuitive performance characteristics.  Also, it could potentially lead to people trying to use selectors to get the "current" state without proper state changes, which seems like may be the situation here.  Skimming the issue again to refresh on context, but it sounds like you would like the state to properly update when the URL changes?  If the URL changing is a state change then that should be reflected in the data-flow graph so that derived state and subscribing components are properly notified.  One option may be to subscribe an atom to be updated when the URL changes and then the other derived state can depend on this atom instead of trying to read the URL directly.  That should allow them to be properly notified when the state changes.  In regards to testing, if you are looking for completely isolated state environments perhaps consider unique `<RecoilRoot>` instances for each test, maybe with a `key` prop or other mechanism?  (cc @csantos42)

**Comment by getsaf** [comment]
Agreed that using a different caching strategy in tests would lead to components that act one way in tests but another way in production.

Essentially, just having a way to "nuke" cache would suffice. I can think of multiple ways to do it, but a few pragmatic approaches might allow cache clearing in the `initializeState` callback.

```tsx
<RecoilRoot initializeState={snapshot => snapshot.dangerouslyResetAllCache()}>
  {/* ... */}
</RecoilRoot>
```

All the `dangerouslyResetAllCache` function would need to do is reset all caches created by [`getTreeCache`](https://github.com/facebookexperimental/Recoil/blob/170e9c0800570e5f6aa61e4c26a37c5dac54751a/src/caches/Recoil_treeCacheFromPolicy.js#L51)

Or if you would like to make cache resetting more granular, maybe we could allow access to it via the `node`:
```tsx
<RecoilRoot initializeState={snapshot => {
  for (const node of snapshot.getNodes_UNSTABLE()) node.cache.clear();
}>
  {/* ... */}
</RecoilRoot>
```

One thing to consider is that I would imagine that cache-resetting between tests is something every single user of recoil will want to do in their test environment since state-bleed across tests is pretty-much never desired.

**Comment by drarmstr** [comment]
As the selector caches aren't part of the scope of a snapshot, we wouldn't want to expose that API as part of a Snapshot.  The per-node or global interface would be more applicable.
For testing, also consider creating a fresh selector with a unique key for each run as an option.

**Comment by getsaf** [comment]
@drarmstr thanks, I just poked around a little more in the Recoil source and see what you mean about cache being part of the node, and unrelated to the snapshot.

The global interface (aka @sebinsua's [solution](https://github.com/facebookexperimental/Recoil/issues/972#issuecomment-861336339)) seems more appropriate.

**Comment by drarmstr** [comment]
Current motivations for an interface to explicitly clear selector caches on a per-node basis: 1) For testing to force re-evaluation of selector. 2) To by-pass the contract that selector evaluations are idempotent as a perhaps more intuitive or convenient mechanism for [re-querying async requests](https://recoiljs.org/docs/guides/asynchronous-data-queries#query-refresh), and for security to flush state such as when a user logs out.

**Comment by getsaf** [comment]
This looks nice. If I understand it correctly, it looks like we'd be able to create a component that, on unmount, would iterate through all the store Nodes and [`clearCache`](https://github.com/facebookexperimental/Recoil/pull/1294/files#diff-f75b62372a74e3749bb183b794fe70f0fc292ea2bd664ef50ae7682cc7ee5beaR68) for every selector we find.

Something like this:

```tsx
const RecoilCachResetEntry = ({ node }: { node: RecoilValue<unknown> }) => {
  const resetNode = useRecoilRefresher_UNSTABLE(node);
  useEffect(() => {
    return () => resetNode();
  });
  return null;
};

const RecoilCacheReset = () => {
  const snapshot = useRecoilSnapshot();
  return (
    <>
      {Array.from(snapshot.getNodes_UNSTABLE()).map((node) => (
        <RecoilCachResetEntry key={node.key} node={node} />
      ))}
    </>
  );
}
```

Then just render it in your test component (or integrate into a shared test-wrapper component):
```tsx
render(
  <RecoilRoot>
    <RecoilCacheReset />
    <MyTestComponent />
  </RecoilRoot>
);
```

**Comment by drarmstr** [comment]
Updated semantics in #1302

**Comment by FokkeZB** [comment]
I can confirm that @getsaf 's fix works with 0.5.2, but I did have to add the missing dependency array to `useEffect` or it would get stuck in a callstack loop:

```ts
const RecoilCachResetEntry = ({ node }: { node: RecoilValue<unknown> }) => {
  const resetNode = useRecoilRefresher_UNSTABLE(node);
  useEffect(
    () => () => {
      resetNode();
    },
    [resetNode]
  );
  return null;
};

const RecoilCacheReset = () => {
  const snapshot = useRecoilSnapshot();
  return (
    <>
      {[...snapshot.getNodes_UNSTABLE()].map(node => (
        <RecoilCachResetEntry key={node.key} node={node} />
      ))}
    </>
  );
};
```

**Comment by drarmstr** [comment]
@FokkeZB note also that refreshing all nodes should be simplified with the updated API in #1413  (not yet released)

**Comment by trentmwillis** [comment]
It's been a little bit since I followed up on this, but happy to report that with the new "refresh" API and [this example in the docs](https://recoiljs.org/docs/guides/testing#clearing-all-selector-caches), we were able to get our app upgraded to the latest version of Recoil and all tests fixed/passing.

Thanks to everyone that contributed to this!

**Comment by sebinsua** [comment]
```js
const clearSelectorCachesState = selector({
  key: 'ClearSelectorCaches',
  get: ({getCallback}) => getCallback(({snapshot, refresh}) => () => {
    for (const node of snapshot.getNodes_UNSTABLE()) {
      refresh(node);
    }
  }),
});

const clearSelectorCaches = testingSnapshot.getLoadable(clearSelectorCachesState).getValue();

// Assuming we're in a file added to Jest's setupFilesAfterEnv:
afterEach(clearSelectorCaches);
```

@trentmwillis Where has `testingSnapshot` meant to come from in the example?

**Comment by mikekreisher** [comment]
> Where has `testingSnapshot` meant to come from in the example?

I'm wondering if `testingSnapshot` comes from [this comment](https://github.com/facebookexperimental/Recoil/issues/1480#issuecomment-1037220934):

```
afterEach(() => {
  const snapshot = snapshot_UNSTABLE();
  snapshot.getLoadable(clearSelectorCachesState).getValue()();
});
```

so `testingSnapshot` may be defined with `const testingSnapshot = snapshot_UNSTABLE();`
